### ISSUE TITLE
Performance about 20% worse than "native" client

### ISSUE THREAD

**Issue by realAbitbol** [seathasky/FF14-MAC_ModSupport#11]
## System 
<img width="587" alt="image" src="https://user-images.githubusercontent.com/73762857/140453709-b2826618-4a14-4235-9bd1-6967bc2713bd.png">

## Crossover (Legit version used, trial)

<img width="782" alt="image" src="https://user-images.githubusercontent.com/73762857/140452241-695f3929-e4b2-4d3e-83a7-6fbf0f96e140.png">

## Game settings (identical for "native" and crossover)

<img width="756" alt="image" src="https://user-images.githubusercontent.com/73762857/140452971-1116afb3-ec99-4c39-9fbf-71b1f81f8e25.png">
<img width="756" alt="image" src="https://user-images.githubusercontent.com/73762857/140452999-155e872e-606f-4297-a693-7c1aabd63b45.png">
<img width="756" alt="image" src="https://user-images.githubusercontent.com/73762857/140453031-66a34be9-42f5-4638-8fe8-598e29745d40.png">
<img width="756" alt="image" src="https://user-images.githubusercontent.com/73762857/140453051-635770c1-14ab-4990-b996-bc9c36084757.png">

## Steps run to reproduce the problem :

- Uninstall crossover with the codeweavers provided automator script ( https://www.codeweavers.com/support/wiki/mac/mactutorial/uninstall )
- Install crossover 21 from the publisher's website
- Download the ffxiv on mac script : https://github.com/marzent/ffxiv-on-mac/archive/refs/heads/main.zip
- Run install.sh
<img width="417" alt="image" src="https://user-images.githubusercontent.com/73762857/140452108-011fd3fd-1abb-492b-a455-4e238121b069.png">

- Run the crosstie to create the bottle and install the game
- Select DirectX 11
- Disable injection
- Quit game as soon as launched
- Edit cxbottle.conf
<img width="569" alt="image" src="https://user-images.githubusercontent.com/73762857/140452396-13123a12-20c3-45f1-bc67-6ad5a1cab59f.png">

- Edit bottle settings
<img width="456" alt="image" src="https://user-images.githubusercontent.com/73762857/140452500-ef8c9311-37a4-45e7-9d8f-4069d8076af5.png">

- Run FFXIVLauncher from the bottle
- Ensure injection is disabled
<img width="487" alt="image" src="https://user-images.githubusercontent.com/73762857/140452713-2b32e454-4fc4-4661-a1f0-aa29e12936cb.png">

- Go to residential district in game
- Performance "Crossover" : 40 fps
<img width="215" alt="image" src="https://user-images.githubusercontent.com/73762857/140453123-ff87ad3e-e20f-4289-a776-1a4c9ded6b41.png">

- Close the game and crossover
- Run "native" client
- Don't move at all in order to stay at the same place in game, same graphic settings
- Performance "native" : 54 fps
<img width="215" alt="image" src="https://user-images.githubusercontent.com/73762857/140453451-37410bc7-ed40-4be1-989d-9f024e7d4680.png">

I'm available to run any tests you require to narrow down the problem.
Thanks a lot for your help and for your awesome work.

**Comment by seathasky** [comment]
Heading to bed now. Me or @marzent will look into this tomorrow.

**Comment by realAbitbol** [comment]
Gnite, feel free to reach to me if needed

**Comment by marzent** [comment]
Would be interesting to see if the performance drop also occurs without patching CrossOver, in the steps to reproduce the problem it is not really needed…
You could also maybe disable dxvk's hud though that is kinda grasping at straws, feel free to hit me up on Discord (ウサギ#4334) prob easier to find a solution that way

**Comment by realAbitbol** [comment]
Will do ASAP
Included the crossoverpatch because I want to be able to run plugins. Just didn't included them in the tests so that the comparison was as simple as possible

**Comment by realAbitbol** [comment]
Disabled dxvk HUD by commenting the "DXVK_HUD" = "fps" line : Same performance (40 fps)

**Comment by seathasky** [comment]
Try the latest nightly here. Close crossover completely and copy the nightly on top of Crossover.app in application folder. Next launch, cx will update (should work on trial, hopefully) if not scratch this idea

https://drive.google.com/file/d/19RlxCcUkfx8CmXPk5I4xHrbq_hVZIiCr/view?usp=sharing

You dont need to change anything in your prefix

**Comment by realAbitbol** [comment]
@marzent 
Sent you a friend request on Discord

**Comment by realAbitbol** [comment]
> You dont need to change anything in your prefix

What do you mean by prefix ?

**Comment by seathasky** [comment]
the physical directory where your bottles are, just overwrite the Crossover.app with the nightly one and reopen it and an update should prompt (if it works on trial)

**Comment by realAbitbol** [comment]
Did it (works with trial).
unfortunately performance stays the same 

<img width="166" alt="image" src="https://user-images.githubusercontent.com/73762857/140500134-acf6605b-3d1e-4210-aa06-f5e7d8ea5299.png">

**Comment by seathasky** [comment]
I'm assuming you're on a hackintosh right?

**Comment by realAbitbol** [comment]
Not at all, I'm on a genuine iMac 5k from 2017 (the biggest model with i7 and Radeon Pro 580) 
https://support.apple.com/kb/SP760?viewlocale=en_US&locale=en_US

**Comment by seathasky** [comment]
ohh! Hey trying running the game in 1080p (Fullscreen) if you can, the 580 is going to struggle getting frames at 5k res. Even a 5700 XT would have problems running at that resolution.

I can almost guarantee this is your issue.

**Comment by realAbitbol** [comment]
It works much better in fullscreen but I'd really porefer to run it in fullscreen borderless.
Furthermore "native" version works this way pretty fine.
Both get a performance boost if I change the screen mode but native always is ahead fps-wise

**Comment by seathasky** [comment]
I'm just saying, dont expect much more than that with addons running at 5k in borderless with a 580 and a 7th gen i7. Bottleneck city if you ask me.

If you want the best of both worlds, lower your desktop resolution to 1080 and than run in borderless... install gshade, you can pretty up your game that way without worrying about frame drops.

**Comment by realAbitbol** [comment]
I understand but currently I run without any addons and yet there is a significant performance drop.
Will do what you said once we figure out what the problem is.

**Comment by seathasky** [comment]
remove these last 3 env variables from you bottle config, reboot cx and test for me please 
![Screen Shot 2021-11-05 at 7 55 19 AM](https://user-images.githubusercontent.com/17598024/140506841-8acee716-ee54-4954-a8f9-488d64fdf2e3.png)

you dont even need harmony debug anymore anyways. pretty sure dalamud fixed that (dont quote me)

**Comment by realAbitbol** [comment]
Actually @marzent asked me to do that on discord, did it but no change

**Comment by seathasky** [comment]
Alternatively you can try https://github.com/Gcenx/WineskinServer  here if you haven't already, but you will have to install all the dependencies manually inside winetricks & the custom dxvk_macos.verb as well. 

Personally, I dont know what else to try at this point, outside of a fresh Macos install, your performance should be going up in cx21, not down. 

I dont know what else to suggest.

**Comment by realAbitbol** [comment]
Tried a whole bunch of things with @marzent on Discord but, unfortunately, it didn't change anything.
I might try to do a full reinstall of macos as you suggested but it's a bit complicated because I'm using my mac to work too.

What would be really helpful at this point would be having info from other users running with a radeon pro 580 or 570.
If anyone has better perf than native  it would mean it would really be worth the hassle.

**Comment by realAbitbol** [comment]
> ohh! Hey trying running the game in 1080p (Fullscreen) if you can, the 580 is going to struggle getting frames at 5k res. Even a 5700 XT would have problems running at that resolution.
> 
> I can almost guarantee this is your issue.

I'm not running at 5k res : because it's a retina res it's effectively running at half which is 2560x1440 AKA 1440p

**Comment by seathasky** [comment]
Well that's what i am saying. You are the first to have such issues which makes me think it's just either bottleneck or some other issue.

As far as others with your same setup, that might be rough. I do have an older Mac with Catalina and a 580 4gb card, but it has a 4th gen i5 and is sitting in my closet collecting dust. I might pull it out tonight and test for you though, I'm curious how it would run. If I get better performance with this thing than you it might narrow down that there is an actual issue on your side

**Comment by seathasky** [comment]
I ended up pulling it out and going to test on it 
![Screen Shot 2021-11-05 at 6 55 28 PM](https://user-images.githubusercontent.com/17598024/140587108-a4210bbf-d8d7-4e09-b981-52a8614e209e.png)

**Comment by seathasky** [comment]
![Screen Shot 2021-11-05 at 7 08 49 PM](https://user-images.githubusercontent.com/17598024/140588010-59f0462c-b353-4b47-98e4-987739bbe65a.png)
This is on a worse setup than yours @realAbitbol slower ram, slower cpu, less gpu memory. and I get 60-120 fps depending on where I am. with plugins enabled

**Comment by seathasky** [comment]
oh shit just realized esync was off let me test with it on

**Comment by seathasky** [comment]
okay this is in the open world, with exact same settings that you showed
![Screen Shot 2021-11-05 at 7 29 42 PM](https://user-images.githubusercontent.com/17598024/140589030-b738977f-a73f-4685-abd9-361e6230fcd7.png)
![Screen Shot 2021-11-05 at 7 30 57 PM](https://user-images.githubusercontent.com/17598024/140589186-b6d753b1-2755-4cfb-a8af-aaacea9b02ce.png)
![Screen Shot 2021-11-05 at 7 32 23 PM](https://user-images.githubusercontent.com/17598024/140589196-e0b3b603-7251-441a-924a-803486ac2a5a.png)

Here is with even more plugins installed and delvui which is in beta still:
![Screen Shot 2021-11-05 at 7 44 34 PM](https://user-images.githubusercontent.com/17598024/140589940-2a8592e8-2aa9-4ec6-b496-7a6062f84dcf.png)


and this is with dalamud plugins turned off in same spot:
![Untitled](https://user-images.githubusercontent.com/17598024/140590250-541d2e39-0a1e-481d-958d-bf5e0f2482b0.png)



This is all with a way worse setup than you and plugins running. Your next step would be a fresh macOS install.

**Comment by realAbitbol** [comment]
I'll do that then, thanks a whole lot for your help !

Will report here once it's done of course

**Comment by realAbitbol** [comment]
Just a question : were you running 1440p ?

**Comment by seathasky** [comment]
1080p throughout the test

**Comment by realAbitbol** [comment]
That might explain, will try in 1080p right now

**Comment by seathasky** [comment]
Didn't I mention for you to do that earlier? haha

**Comment by realAbitbol** [comment]
In the beginning I think I mixed things up and thought I was in 1080p in fullscreen borderless but that's impossible unless I changed the desktop resolution which I didn't.

On my iMac screen fullscreen borderless runs at 1440p we even saw that in logs with marzent

**Comment by seathasky** [comment]
> If you want the best of both worlds, lower your desktop resolution to 1080 and than run in borderless... install gshade, you can pretty up your game that way without worrying about frame drops.

I did say this too :)

**Comment by realAbitbol** [comment]
I know but as I and marzent think my setup should handle 1440p easily. It even does with native.
I know I could drop the res a ton and get things working somehow but in that case it would be better to just run native with 1440p

**Comment by realAbitbol** [comment]
getting 50 fps in 1080p. THat's better but nowhere close to you.
I'll reinstall macos.

Do you think I can restore with my timemachine backup or should I really start from a blank plate ?

**Comment by seathasky** [comment]
Ya you should be getting way more fps than my old machine, its only a 4th gen i5 and 4gb card, there is def something wrong.

**Comment by realAbitbol** [comment]
Forgot to mention that I'm running with a 2nd 4k screen attached (unused by the game tho)

**Comment by seathasky** [comment]
You could always try unplugging the dp cable and test with 1 monitor before you format

**Comment by realAbitbol** [comment]
I'll do that but it would puzzle me because native works fine with it.

**Comment by seathasky** [comment]
![1yj28o](https://user-images.githubusercontent.com/17598024/140596807-83112c06-74bb-4950-ae44-1bc9966e5da5.jpg)

**Comment by realAbitbol** [comment]
No change, I'll reinstall macos from scratch now, not using my timemachine backup. It will be painful but, hopefully, worth it.
See you on the other side xD

**Comment by seathasky** [comment]
I really do hope it fixes the issue, if not I dont know what else you could do

**Comment by realAbitbol** [comment]
Know I really appreciated the help of both of you

**Comment by realAbitbol** [comment]
Completely reinstalled macOS Big Sur from scratch without using my time machine backup.
Bare minimum install : no additional software installed except Crossover 21 and Textmate.
Redid the whole procedure from scratch.

Result : performance **_might_** be a tad higher but nowhere near native or near your results.
Game somehow feels sluggish even with 50 fps.
Game is kinda playable but there are random hiccups when I move or fight, the kind I don't really want to see while raiding :(

I think there is either something fucked up with my hardware (unlikely cause native works fine) or some kind of incompatibility between this version of moltenvk  and my precise model of graphic card...

Only thing I could try for now would be trying to go Monterey but I'm not sure XIV works fine with it or buy a new shiny pro max MacBook pro but I'm not sure XIV works all that well on it (compared to native with my current setup).

EDIT : cleared SMC and NVRAM, no change

**Comment by seathasky** [comment]
Did you let shader cache build? Use abilities, run around to different spots for at least 30 mins.

**Comment by marzent** [comment]
Last thing I would suggest is transplanting the dxvk used with the "native" version into the cx 21 bottle and you would (probably?) see no performance difference

**Comment by realAbitbol** [comment]
I'll try that.
I've noticed I can tell even from the login screen if I'm running native or CX : the mouse pointer kinda jumps on CX

**Comment by seathasky** [comment]
Technically, you should be seeing more performance over my old i5 closet machine as your machine has better everything...I'm sorry we were unable to help you.

I dont really know at this point and dont think we will be able to assist you any further.
I'd try marzents last comment at the very least and my last comment of letting the dxvk shader cache build.

**Comment by realAbitbol** [comment]
I'll try that too @marzent I'll message you on discord for the transplantation as I have no idea on how to do it once I reinstalled discord if you don't mind

**Comment by realAbitbol** [comment]
Transplantation didn't go so well (game crashes) , Marzent gonna run some tests tonight.
Meanwhile I'm trying a Monterey upgrade to check if it works better with it

**Comment by seathasky** [comment]
Better performance by downgrading libMoltenVK.dylib compiled and provided by @marzent.
Closing this issue for now as solved.
