### ISSUE TITLE
Do I need to have FFXIV installed on Mac prior to using this guide?

### ISSUE THREAD

**Issue by seenasa** [seathasky/FF14-MAC_ModSupport#12]
Trying to install the game following the guide on a brand new MacBook Pro M1 Max and the installer seems to be stuck on "waiting for download". Also, I wasn't clear on whether to enable in game features, so I left it checked. Thanks for your help and for creating this guide!

<img width="340" alt="Screen Shot 2021-11-08 at 12 40 25 AM" src="https://user-images.githubusercontent.com/15369952/140710244-77f72c15-f06e-448a-b9f2-a940e6a569f3.png">

<img width="768" alt="Screen Shot 2021-11-08 at 12 40 47 AM" src="https://user-images.githubusercontent.com/15369952/140710297-42678876-8a54-4a09-81dd-54e2c52c9f88.png">

**Comment by seathasky** [comment]
Try changing the patching method in the launcher: 
![Screen Shot 2021-11-08 at 10 36 43 AM](https://user-images.githubusercontent.com/17598024/140771489-6395c4b1-f4ee-4554-8569-0fe841c3f218.png)

**Comment by seenasa** [comment]
Changing the method worked but after about an hour of downloading it crashed with this error

<img width="1348" alt="Screen Shot 2021-11-08 at 12 40 27 PM" src="https://user-images.githubusercontent.com/15369952/140815047-cbc28c2c-94ca-4fa4-b9f9-c9a2291b2c24.png">

**Comment by seathasky** [comment]
Make sure you have all 3 of these settings checked 
![Screen Shot 2021-11-08 at 5 32 06 PM](https://user-images.githubusercontent.com/17598024/140828676-20fec014-2ee5-4f88-b5aa-626004978446.png)

**Comment by seenasa** [comment]
I enabled performance enhanced graphics, dxvk backend for d311 and performance enhanced synch, and didn't get the fatal error but the frozen black screen. I followed the instructions to change the openingcutscene value to 1 and restarted the game but got the fatal error again.

**Comment by seathasky** [comment]
Try restarting and resetting nvram and report back

**Comment by seenasa** [comment]
reset the NVRAM using the terminal command in recovery mode and rebooted, am getting the same black screen. It's been about a minute and no crash yet. Any ideas on how to fix this? I also noticed that there is no folder for crossover along the application support path for step 2 performance tweaks.

edit: just restarted and got the crash

<img width="1348" alt="Screen Shot 2021-11-08 at 3 42 07 PM" src="https://user-images.githubusercontent.com/15369952/140835660-004d0a83-0111-4090-ab30-cd6446bd5f39.png">

**Comment by seathasky** [comment]
Other M1 users are having success with our setup guide. I havent encountered this error with a user before who is on M1, so I dont know where to start. 

https://www.reddit.com/r/macgaming/comments/qiuwew/ffxiv_late_game_benchmarks_m1_pro/

I would make a comment on this post regarding your issue and maybe the original poster can assist you on how he got it to work with our guide. I don't personally own an M1 machine to help test with you.

**Comment by seathasky** [comment]
There is a folder, you are just looking in the wrong place. As far as finding your folder make sure you unhide files (  cmd + shift + . )  It's in the user's Library

![Screen Shot 2021-11-08 at 6 58 25 PM](https://user-images.githubusercontent.com/17598024/140837108-3cdffe62-09f1-4c16-880a-ef8376616908.png)

**Comment by seathasky** [comment]
I'm going to assign our developer @marzent to this and see if he can help you

**Comment by seenasa** [comment]
Thanks for your help. I was able to find the the files, and added the code in and now there's just a black screen with an fps counter, without the loading bar, no crash yet

<img width="1392" alt="Screen Shot 2021-11-08 at 6 13 59 PM" src="https://user-images.githubusercontent.com/15369952/140849273-3d7957d8-7edd-4576-8c53-d3fd8857c886.png">

**Comment by seenasa** [comment]
Okay, I got the game to run after playing around with some of the settings.

I switched to a Windows license (i have both, and it didn't work), and then I switched back to the Mac and disabled "enable in-game features". Is having that disabled cause issues such as duty finder pops?

 I'm getting pretty solid FPS (around 60-80 in New Gridania and up to 120 outside according to the overlay in the top left corner), but I have it locked at 60, and seems to be stuttering a lot. Is that to be expected?

**Comment by seathasky** [comment]
In the next few days we will have some pretty ground breaking updates to the project which include, updating dxvk (which Crossover doesnt even do yet). @marzent has been working hard to improve the project were doing and we're seeing some astounding results so far with some of the additions he's doing. We just haven't released them to the public yet as we're still testing stuff (soon TM)

To answer your question, the upcoming changes should fix the stuttering (in theory)
![image0](https://user-images.githubusercontent.com/17598024/140851470-b39fb4c4-fcf9-447a-be6a-dfe4faa80a66.jpg)
This is in the latest version of DXVK that @marzent compiled and we're seeing lovely results from it. Keep a look out, we will update the news page when its available.

I'm glad you got the game running in the meantime. As far as "In-Game-Features", this is for plugin injection. If you turn this feature off, you cant use Dalamud plugins.
https://goatcorp.github.io/DalamudPlugins/plugins.html
(like WoW addons basically)

Also, dont lock your FPS.

**Comment by seenasa** [comment]
That's super exciting, thanks a bunch for all the support!

I'm a layman when it comes to tinkering with software like this and planning to play the game without any add-ons (not sure what any of the plugins are). So to clarify, it won't affect any of the basic features of the game? I also wasn't sure what was meant by using the patcher. 

As far as in game settings go, when selecting a resolution, would I select (e.g. 1920x1200 60hz)? and no fps limit at the bottom? I thought it would act similarly to V Sync if I locked my FPS a little lower and deselected promotion in the macs display settings. Lastly, are there any other in game settings you'd recommmend switching or links to other posts that show optimized settings

**Comment by seathasky** [comment]
You dont need plugins in the game at all. They are all QoL stuff anyways, nothing game breaking. On or off dont affect the game in any way. They for personal use.

capping fps with ff14 through crossover is kind of buggy at the moment and can actually lower your fps and cause stuttering. I would advice not doing it. 

In game doesnt matter as much, it really depends on what your personal setup can handle tbh and what you are comfortable with. I try and find a happy middle ground between graphics and fps. Mess around with the settings to your liking.

**Comment by seathasky** [comment]
Going to close this issue for now since your game is running, keep an eye on updates soon

**Comment by seenasa** [comment]
Hi @seathasky i just tried launching the game and got the same blackscreen fatal error after seeing the notification that there had been an update to the launcher. Not sure what to do but im reinstalling using the new m1 specific launcher. Please advise, ty!

Now there is 2 ffxiv launcher bottles and neither seem to work. Pressing the login button is unresponsive at the login screen
