### ISSUE TITLE
Black screen on launch after MoltenVK update for M1 Users. SOLVED

### ISSUE THREAD

**Issue by jordanearle** [seathasky/FF14-MAC_ModSupport#13]
Hey, 

Just did a clean install following the new instructions with the latest script and I'm having issues starting the game. 

The game has worked.. a few times, but 95% of the time the launcher opens and I get a black screen with the FPS counter. No Square Enix logo and the game doesn't proceed past this point. 

This is on a new M1 Pro MacBook Pro using Crossover 21.

No mods, just followed all relevant steps to install and then jumped to step 8 to finish. Using a Windows license.

**Comment by seathasky** [comment]
~~this is covered in our troubleshooting section: https://github.com/seathasky/FF14-MAC_ModSupport#troubleshooting~~

**Comment by marzent** [comment]
Are you using the newer MoltenVK version by chance?

**Comment by seathasky** [comment]
Do you happen to see the loading wheel in the bottom right corner? Or is everything just black?

**Comment by jordanearle** [comment]
> Do you happen to see the loading wheel in the bottom right corner? Or is everything just black?

All I see is the FPS counter, which seems to be in the lower single digits ranging from 0.6 - 2.9? No spinning wheel or logo.

**Comment by jordanearle** [comment]
> Are you using the newer MoltenVK version by chance?

Not sure, It's a fresh install based on the latest script which I downloaded yesterday.

**Comment by jordanearle** [comment]
It seems to be working slightly more reliable if I force it to use DirectX 9 in the FFXVI_BOOT file by setting DX11Enabled to 0...

On occasion I've also seen a DX11 fatal flaw message.

**Comment by seathasky** [comment]
Unfortunately, Square Enix themselves dont support M1 processors for this game. We've seen plenty of people w/ M1 chips use our guide with success but as far as troubleshooting, me and Marzent are both Hackintosh users, so support from us will be limited. 

We've been seeing very positive feedback from M1 users on Reddit from using our guide. Here's one example:
![Screen Shot 2021-11-09 at 11 06 29 AM](https://user-images.githubusercontent.com/17598024/140960529-aa1464fd-5430-41df-9c40-3c4aea83c6d1.png)

I would try over, maybe you missed something in the install guide?

**Comment by adamfail** [comment]
I do want to note that I had the exact same issue described above until I removed the MoltenVK update. After removing MoltenVK, FFXIV launches just fine. I hope this helps.

**Comment by xilkoi** [comment]
Same thing happened with me. Oddly, it all seemed to run just find yesterday with the MoltenVK update, but it stopped working (exhibiting the same symptoms Jordan noted) today until I reverted to the backed-up version. I am also on an M1 Pro MacBook Pro.

Out of curiosity, since I keep a stock FFXIV install on my machine, I poked through the files for it and tried to input the MoltenVK update into the stock version and experienced the same symptoms until I reverted.

**Comment by seathasky** [comment]
> I do want to note that I had the exact same issue described above until I removed the MoltenVK update. After removing MoltenVK, FFXIV launches just fine. I hope this helps.

This is very useful information Adam! I will put a warning on updating MoltenVK for M1 users! Thank you!

**Comment by seathasky** [comment]
Updated Step 1 with warning for M1 users upgrading the our newer MoltenVK. Reverting to CX21's shipped MoltenVK fixes issues.

**Comment by jordanearle** [comment]
Reinstalling with a new bottle and skipping the upgraded Molten VK worked, thanks! Hopefully it gets updated so the M1 can have the 25% performance boost.

**Comment by seathasky** [comment]
We have other things in the works. Keep an eye on the updates here

**Comment by marzent** [comment]
Weird you having an issue with MoltenVK shouldn’t really be happening as it’s pretty much the stock version with faking two extra extensions for dxvk…
Feel free to try different patched versions from the release section [here](https://github.com/Gcenx/MoltenVK) you can even find version 1.1.3 CrossOver ships with in there (if you ever were to lose your backup)

**Comment by adamfail** [comment]
I tried both 1.1.5 and 1.1.4 on the releases page. Version 1.1.4 worked and version 1.1.5 did not. 

The working release was titled "Release for Vulkan SDK 1.2.182" and downloaded "macos_dxvk_patched.tar.xz." 

I replaced libMoltenVK.dylib found in /Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64 with the libMoltenVK.dylib found in the downloaded tar.xz. 

I am unsure if this is the correct way to do this and I have not extensively played the game with this patch applied. 1.1.5 would just present a black screen with the FPS display around or under 1 FPS while 1.1.4 lets me login and walk around fine. I hope this helps.

**Comment by seathasky** [comment]
Thanks for the info @adamfail 

I'm thinking for the time being, we will need to have 2 different installers. One for M1 Macs and another for Intel Macs. Will try and have that up this weekend on the guide or another method.

**Comment by kailred** [comment]
i have been racking my brain all morning trying to figure this out, because the game worked fine last night but today it won't. I'm glad someone just posted about reverting to 1.1.4. I'm going to give that a shot now. Macbook Air M1.

**Comment by seathasky** [comment]
> i have been racking my brain all morning trying to figure this out, because the game worked fine last night but today it won't. I'm glad someone just posted about reverting to 1.1.4. I'm going to give that a shot now. Macbook Air M1.

Ya, we just updated Step 1 for M1 users, sorry for the frustration. Unfort, both me and Marzent dont have access to M1 machines. So it's all trial and error at this point.

**Comment by kailred** [comment]
No frustrations. Rolling back to 1.1.3 as directed in the previous person's comment did the trick exactly.

Grateful for all the hard work and progress. Even without the 25% boost from the MoltenVK, I'm still getting much better FPS (by 10 or so) and better response from the mouse.

Looking forward to where this goes! :)

**Comment by seathasky** [comment]
![Screen Shot 2021-11-10 at 1 03 22 PM](https://user-images.githubusercontent.com/17598024/141168250-b04a54ff-b04e-49c1-8dcc-e1e836c2968b.png)

**Comment by seathasky** [comment]
> No frustrations. Rolling back to 1.1.3 as directed in the previous person's comment did the trick exactly.
> 
> Grateful for all the hard work and progress. Even without the 25% boost from the MoltenVK, I'm still getting much better FPS (by 10 or so) and better response from the mouse.
> 
> Looking forward to where this goes! :)

We will be releasing more performance enhancements soon, so keep an eye on the page, already seeing positive feedback from some users who have tested for us. Hopefully this weekend!

**Comment by seathasky** [comment]
@kailred did you ever test out 1.1.4 or did you roll back to 1.1.3?

**Comment by kailred** [comment]
i did not test 1.1.4, but i will be glad to do so within the hour :)

**Comment by seathasky** [comment]
ty soo much, i'm going to consolidating files for intel and m1 users and need to know if its even worth having 1.1.4 for m1 or just have them use 1.1.3. i cant test so i appreciate your help

**Comment by kailred** [comment]
was able to switch to 1.1.4 from 1.1.3 just now and the game operates normally. glad to help anytime

**Comment by seathasky** [comment]
@kailred ty! Keep testing and report any issues you have. We will probably go with that for m1 users.

**Comment by seathasky** [comment]
M1 users now have their own version of ffxiv-on-mac patcher which includes moltenvk 1.1.4 update. https://github.com/marzent/ffxiv-on-mac/tree/m1

**Comment by Gcenx** [comment]
Once MoltenVK-v1.1.6 release is tagged (and stable) I’ll push new packages, if this still occurs when using DXVK it’s time to open an issue with upstream MoltenVK.

Interestingly I’ve seen lockup’s with Witcher3 (GPU Lost) when using MoltenVK-v1.1.5 & DXVK but not when using WineD3D Vulkan but I’m assuming FF doesn’t run properly with that?

The attached MoltenVK-CX21 package is a source compile not a CodeWeavers provided prebuilt binary.

**Comment by seathasky** [comment]
> Once MoltenVK-v1.1.6 release is tagged (and stable) I’ll push new packages, if this still occurs when using DXVK it’s time to open an issue with upstream MoltenVK.
> 
> Interestingly I’ve seen lockup’s with Witcher3 (GPU Lost) when using MoltenVK-v1.1.5 & DXVK but not when using WineD3D Vulkan but I’m assuming FF doesn’t run properly with that?
> 
> The attached MoltenVK-CX21 package is a source compile not a CodeWeavers provided prebuilt binary.

It seems only an issue on certain setups and mainly localized with m1 users. We did have 1 intel user not able to use it though, as it caused the same issue in FF. Both me and Marzent are on newer intel hardware with navi gpus (hackintoshs) and 1.1.5 works fine for us. So it could have something to do with older hardware for the 1 intel user who had issues with it as well. Looking forward to 1.1.6, hopefully it fixes this issue for m1 users

As far as us, were both able to run 1.9.2 and 1.1.5 without issues.

**Comment by Gcenx** [comment]
I believe this affects M1 and Nvidia cards along with some ancient AMD GPUs.

But yeah if I still get the issue on Witcher3 I’ll be opening a new issue linking back to the old closed issue. Too bad CX21.1 beta is happening as Chip would be invaluable for tracking this down.

If anyone is reading this who has an M1 system you can always try the latest MoltenVK commit just grab it from the most recent actions run.

**Comment by marzent** [comment]
> Interestingly I’ve seen lockup’s with Witcher3 (GPU Lost) when using MoltenVK-v1.1.5 & DXVK but not when using WineD3D Vulkan but I’m assuming FF doesn’t run properly with that?

It is more performant on the title screen, but it doesn't render any 3D models on character selection and also no PCs or NPCs in the open world with pretty bad performance.
