### ISSUE TITLE
Users with Mac Licence cannot log in after update?

### ISSUE THREAD

**Issue by seathasky** [seathasky/FF14-MAC_ModSupport#15]
After XIVLauncher updates, the Mac client will break and revert to "Wine On Linux", this is technically fixed but we're waiting on a pull request from Goat over at XIVLauncher. This is also covered in our guide and on Marzents page if you missed it. This WILL happen every XIVlauncher update until Goat (xivlauncher dev) adds @marzent's fix.

In the meanwhile, Marzent has come up with a work around and this problem should rarely happen again if only briefly. 

<h2>Download and re-install using the "XIVLauncherWine.exe" file.</h2>

Reinstall XIVLauncher with our custom installer here, make sure it's the latest version: https://github.com/marzent/FFXIVQuickLauncher/releases/

---

After installation, your xivlauncher client should read "Wine On Mac".

![Screen Shot 2021-11-11 at 6 49 49 AM](https://user-images.githubusercontent.com/17598024/141294173-16ab8716-65eb-47c7-96fa-f5d0995fca01.png)

If it still says "Wine on Linux" your client is still using the windows installer and you need to reinstall with our fix.

---

Alternatively, you can check to see if your actual game is running on the Mac license via graphics settings:
![Screen Shot 2021-11-11 at 7 56 01 AM](https://user-images.githubusercontent.com/17598024/141301881-e72f819e-f26f-4319-8282-a135fcde0349.png)

**Comment by kailred** [comment]
having some trouble figuring out how to install this quicklauncher link posted into my bottle. nothing changes after i install it.

here's my process: fresh bottle via custom installer > install updated xiv quick launcher via crossover linked above > open quicklauncher from crossover > same error message.

not sure if I'm doing something wrong? or if i should be drag/dropping the quicklauncher somewhere so that it installs WITH the fresh bottle, as opposed to installing it after?

**Comment by marzent** [comment]
you don't need a fresh bottle to update XIVLauncher, just rerun [XIVLauncherWine.exe](https://github.com/marzent/FFXIVQuickLauncher/releases/download/6.0.12/XIVLauncherWine.exe) inside the bottle you were using, if you can see Wine on Mac and the correct version in the titlebar you know it worked (assuming you are not running a windows license then you are prob having a different issue altogether)

**Comment by kailred** [comment]
forgive my delayed response - i am not the savviest when it comes to the more technical side of this. I'm not entirely sure what I was doing before, but It's working now that I'm running the updated .exe as a command in the bottle created by your custom installer.

Thanks for all the continued support!!

**Comment by seathasky** [comment]
It's okay! No worries! CX can be confusing at first if you're not use to it, for next time, if you want to include new programs into your FF14 bottle, make sure you highlight your bottle like so, or else it defaults to a new bottle:

![Screen Shot 2021-11-11 at 5 54 39 PM](https://user-images.githubusercontent.com/17598024/141380910-85943c67-e4c5-4099-8b24-a6e7c1eb0b68.png)


I'm pleased you got it working!

**Comment by KoB-Kirito** [comment]
What do I do if I only have a windows licence?
I had the launcher saying linux and did this, then I have the one saying mac, but I have this error:
<img width="1029" alt="Bildschirmfoto 2021-11-12 um 15 56 12" src="https://user-images.githubusercontent.com/51691757/141487883-ed18b79c-557d-4064-b363-f7b52b86a134.png">

I guess because I only have the windows licence. But when I change the setting in the registry the launcher is saying linux afterwards. If I install this exe it resets the setting in the registry..

**Comment by KoB-Kirito** [comment]
Nevermind, it says Linux when changing the registry setting, but works..

**Comment by seathasky** [comment]
Wine on Linux = Windows license

Wine on Mac = Mac license

**Comment by Pavo-IM** [comment]
@seathasky Tried running the latest Setup.exe from your link and error
![Screen Shot 2021-11-12 at 11 57 43 AM](https://user-images.githubusercontent.com/33814640/141505186-dfda901b-d15a-4f64-ae99-b557b11d4fc6.png)

**Comment by seathasky** [comment]
![Screenshot_20211112-115910_GitHub.jpg](https://user-images.githubusercontent.com/17598024/141505395-6dbf09bf-8872-4e7a-a2bc-b8f69ed6b61e.jpg)

**Comment by Pavo-IM** [comment]
Ah my bad, thanks.

**Comment by Pavo-IM** [comment]
Well that broke it, now getting communication error.
![Screen Shot 2021-11-12 at 12 10 01 PM](https://user-images.githubusercontent.com/33814640/141506810-5dff02da-9d54-40fd-9ee8-bda82dd6172b.png)

**Comment by seathasky** [comment]
Go to patching section and change to Aria if it's on .net

![Screen Shot 2021-11-12 at 1 50 42 PM](https://user-images.githubusercontent.com/17598024/141519590-8d426671-5d49-4d02-be81-46c630e937f9.png)

**Comment by Pavo-IM** [comment]
Figured out the issue, for some reason it messes up when using the installer on my Hackintosh but works fine when using a real Mac, I'll just have to use the updater on my real Mac then transfer the files over to my Hackintosh.

**Comment by seathasky** [comment]
I'm on hackintosh and dont have these issues with a Mac license

**Comment by seathasky** [comment]
The environment shouldnt change anything. Hack and Mac are literally the same OS.

**Comment by Pavo-IM** [comment]
On an AMD type hackintosh, something don’t work so well. But it’s all good I have an alternate method

**Comment by seathasky** [comment]
> The environment shouldnt change anything. Hack and Mac are literally the same OS.

^

**Comment by Guuttan** [comment]
I got the game running on Windows once, restarted it and now it only runs on Mac. (_Wine on Mac_)
I have reinstalled the "XIVLauncherWine.exe" file, the hidewineexports is set to "1" and "Enable in game features" is checked as per the installation guide.

I would appreciate any help :) Thank you.

**Comment by seathasky** [comment]
> I got the game running on Windows once, restarted it and now it only runs on Mac. (_Wine on Mac_) I have reinstalled the "XIVLauncherWine.exe" file, the hidewineexports is set to "1" and "Enable in game features" is checked as per the installation guide.
> 
> I would appreciate any help :) Thank you.

Can you still log into the game or get an error message?

**Comment by Guuttan** [comment]
> > I got the game running on Windows once, restarted it and now it only runs on Mac. (_Wine on Mac_) I have reinstalled the "XIVLauncherWine.exe" file, the hidewineexports is set to "1" and "Enable in game features" is checked as per the installation guide.
> > I would appreciate any help :) Thank you.
> 
> Can you still log into the game or get an error message?

I only get the "This Square Enix account cannot play FFXIV" since I only have the Windows version.

**Comment by seathasky** [comment]
How was the game installed? Crosstie? or through Marzents .exe

**Comment by Guuttan** [comment]
I used the zip file from "Step 1" in your setup guide. Then I used the XIVLauncherWine.exe from marzents comment above.

**Comment by seathasky** [comment]
That is for Mac only. If you have a windows license, follow step 1-2 in my guide and use step 7 for windows license. 

You doing your own steps is why you cant log in.

**Comment by Guuttan** [comment]
I tried that as well but it only launched as Wine on Mac. After that I tried to download Marzents update of the launcher as a fix. But I'll try to reinstall the whole thing again :)

**Comment by seathasky** [comment]
The client defaults to Mac period. If you followed the guide from Step 1-2 and step 7, you should be able to log into a Windows license.

I cant exactly test as I own both licenses. So if something changed, I wouldn't be able to tell. 

I can tell you that my game is running the windows license though based on the launcher and in game settings. 

Nothing has changed from my guide to how I installed my client. So you must have done something wrong.


![Screen Shot 2021-11-17 at 5 39 34 PM](https://user-images.githubusercontent.com/17598024/142293944-6f18f111-e2ce-4660-9cbf-319416cb53dd.png)

**Comment by Guuttan** [comment]
Yeah I'm definitely doing something wrong, hehe. I just for the life of me can't figure out what. 

I followed your installation guide to a T this time. The only thing that might differ is the install commands. I chose not to Parse FFXIV data, but enabled plugin injection for the windows license. After that I chose the 2 option because I'm running on a M1 MacBook Pro.
Also I'm running Mac os Monterey, could that be an issue?

Anyways, here's a screenshot of what I'm seeing.

![Skärmavbild 2021-11-17 kl  23 53 08](https://user-images.githubusercontent.com/94569903/142295739-0e988e1c-0335-4ec5-a361-ec734763a52f.png)

**Comment by marzent** [comment]
No need to reinstall, HideWineExports is not working for you (has nothing directly to do with the launcher)
You have 2 options to fix this:

1. (Temporary) navigate inside your Bottle into the `users/crossover/Local Settings` folder and delete Xivlauncher. 
Reinstall the 6.0.9 (not .12) version from my fork afterwards 
2. make sure you have the correct version of ntdll.dll inside crossover, if in doubt rerun the install script and say yes to plugin injection and windows license and skip the rest. 
Afterwards check if the ntdll.dll inside the system32 folder is above 2MB inside. 
Thirdly make absolutely sure that you set the registry key correctly

**Comment by marzent** [comment]
Basically Wine on Mac = found wine exports = Mac authentication
From your screenshot it looks like your registry is fine, I would check the 2 ntdlls next

**Comment by Guuttan** [comment]
I ran the installation with the plugin injection and windows license only and my ntdll.dll is 2.9mb. So it doesn't appear the be that?

It does look like I am running the 6.0.12.0 launcher though, where can I find the 6.0.9 one? Sorry I'm new to both GitHub and Crossover :)

EDIT: I just noticed that you told me to check the "2 ntdlls" next? I can only find one in my system.

**Comment by seathasky** [comment]
Just replace the ntdll in system32 with the one included in the zip and restart crossover and you should be good if you set hidewinexports correctly

**Comment by seathasky** [comment]
I'm going to close this thread.
If you want to use a FF14 windows license instead, make sure you patched for it and follow the guide and not do your own thing.

**Comment by Guuttan** [comment]
I replaced the ntdll.dll file from the folder wine-dlls in the zip file with the ntdll.dll in the system32. Restarted crossover and it still does not work :/

Sorry for the hassle! Could it be the launcher? Should I downgrade?

**Comment by seathasky** [comment]
If you follow the guide from scratch and patch for windows you shouldn't have a problem. As I said before, you didn't follow the guide.

**Comment by Guuttan** [comment]
I have put a lot of hours and effort into this. I have reinstalled it 6 times by now. Checking the guide very carefully every time. I can promise you I have followed it.

If nothing else can be done I thank you for your help and time anyway! The guide is great. But there's something that just doesn't work for me I guess.

**Comment by marzent** [comment]
It will work with the launcher, there’s another ntdll inside `$cxLoc/Contents/SharedSupport/CrossOver/lib64/wine` where cxloc is your crossover app, make sure to overwrite that one as well

**Comment by marzent** [comment]
Also again you really don’t need to waste your time reinstalling every time, it’s a very fixable problem :)

**Comment by Guuttan** [comment]
Omg it worked! Thank you so much :)
