### ISSUE TITLE
Gshade doesn't work

### ISSUE THREAD

**Issue by JanHantschke** [seathasky/FF14-MAC_ModSupport#18]
I installed everything with your Guide and made all the patches when asked in the install script. After I got everything working I tried to install Gshade with the linux install script. I did all the steps and did the dll overrides in the wine settings in crossover. I even checked my installations via the shade install script and my ffxiv installation is marked green so everything should be fine. But when I first tried to launch the game the following error appeared
<img width="501" alt="Bildschirmfoto 2021-11-14 um 21 13 12" src="https://user-images.githubusercontent.com/59010684/141697607-fcb89814-530b-4df6-bfd0-a0902df4bba5.png">
(translated it says something like: The game could not be started, please report this error)

After that I started it again and no error appeared and the game launched, but when I press "shift + F2" to open the Gshade installation nothing happens, I check that the f keys are used and not the function keys (like turn brightness up) and even tried a external keyboard but nothing worked. Also every time I launch XIVlauncher via crossover the launcher title switches from "wine on linux" to "wine on Mac" and I have to do the patches via your install.command again  to revert it back to "wine on linux", because I need to use my windows license.
I hope you can help me, and thanks for your time :)

**Comment by seathasky** [comment]
Marzent will text you on discord
