### ISSUE TITLE
Can't start the program after installation with Molten VK 1.1.5

### ISSUE THREAD

**Issue by Drunemeton** [seathasky/FF14-MAC_ModSupport#19]
**OS:** macOS 10.15.7 (Catalina, fully up-to-date on all system software)
**Macintosh:** iMac20,2 (iMac 5K with Radeon 5700XT: https://everymac.com/systems/apple/imac/specs/imac-core-i7-3.8-8-core-27-inch-retina-5k-2020-20-2-specs.html)
**Crossover:** 21 stable (New purchase, nothing but this installed.)

**Installer:** https://github.com/marzent/ffxiv-on-mac/archive/refs/heads/main.zip
**Installation Method:** https://github.com/seathasky/FF14-MAC_ModSupport
**Installation Options:** Yes to everything, choosing MVK 1.1.5.
**DXVK:** 1.9.2-mac

**Error:**
<img width="347" alt="Screen Shot 2021-11-12 at 1 13 49 PM" src="https://user-images.githubusercontent.com/63975886/141702848-fc049311-a65c-41f3-bd75-6802bf6a5233.png">

First off, thanks for this amazing software! I appreciate the work put into it.

Second, nothing I did following the instructions made any difference. Everything seemed to go fine, launched, entered my creds. + OTP, and immediately received that dialog box. 

EDIT: Actually from the launcher the game window titlebar would draw onscreen, but no border/window below it, then the screen goes black and that dialog box appears.

I joined the Discord link in the launcher and was informed that macOS isn't supported. However a search in the #linux channel turned up a very similar screenshot and a note that downgrading a graphic driver worked. 

So I (for the 7th time) re-installed the software and selected MVK 1.10. Followed the instructions about copying over the DXVK folder, regedit, etc. It worked! But there was a fair bit of stuttering in-game. 

Being a nerd I of course did this again, selecting MVK 1.1.4 and that worked too. This had almost no stuttering, but a bit of noticeable screen tearing in-game whilst turning quickly. 

So is there something I missed about the installation and/or configuration of this software that would allow MVK 1.1.5 work as intended? Otherwise just wanted to you know about my experience in case it can help others. 

Also, happy to help out if you have any updates that need testing. I own both the Mac and Windows Complete Editions (my iMac has bootcamp installed : ) and am happy to help out if needed. 

All my best,
Drunemeton

**Comment by seathasky** [comment]
I use to have a forewarning on the guide saying that nothing is guaranteed. That includes the use of 1.1.5. Should it work with your system? Based on your specs i'd assume so, but there are too many variables to say yes or no still. We had another user who could only us moltenvk 1.0 or his performance would be terrible on anything outside of that. So it's hard to say what your specific hardware likes.  

Also, setup has a lot to do with everything here. Without knowing what exactly got installed during the script + crosstie phase and what exact steps you took, something like this is very difficult to troubleshoot. We've had people who were missing dependencies and wondering why things weren't working or clicking the wrong things after installation. I think my guide assumes too much, which isnt really user friendly at the end of the day, but there is only soo much I can do, so I apologize for that.

For instance, the addition of 1.9.2 dxvk requires that after install you dont reclick dxvk backend. If you do, it will revert dxvk to 1.7 which is essentially a loss in performance.

To clarify, step 2 tells you have all 3 of these items checked, but if you install dxvk 1.9.2 your bottle should look like this instead:

![Screen Shot 2021-11-15 at 1 07 18 AM](https://user-images.githubusercontent.com/17598024/141730884-92986912-f44a-4252-af9d-fb4cd3170efa.png)


Also, not closing Crossover and then installing new things and then trying to run games can cause the game to error out. The project itself can be very sensitive to every little thing you do. It makes sense now why SE hasnt really updated their bottle yet. 1.7 and 1.0 may be slow, but they seem to be the most compatible.

My advice would be to use 1.9.2 and 1.1.4. If you want to use 1.9.2, follow the directions carefully and dont reclick dxvk for backend (assuming you did)

To make sure, inside your "cxbottle.conf" config you can type in the environment variables section at the very bottom: "DXVK_HUD" = "FULL" 

This will allow you to check what dxvk version you are using:
![Screen Shot 2021-11-15 at 1 16 56 AM](https://user-images.githubusercontent.com/17598024/141731926-20f7a7fe-7696-48da-964b-8ca2bdaf0905.png)


I cant really help outside of that as I have no logs to work with

**Comment by Drunemeton** [comment]
Seathasky,

I'm new to GitHub so if replying to a closed issue isn't the correct protocol please let me know and I'll be happy to create a new issue if needed. That being said…

I re-ran the "install.command" and don't see ay option for "don't recheck dxvl for backend" so I'm not sure where this option is located. 

I've changed my "cxbottle.conf" file and the bottom of it is now this:
"WINEESYNC" = "1"
"XL_WINEONLINUX" = "true"
"DXVK_HUD" = "FULL"
"DXVK_FRAME_RATE" = "0"
"GL_SHADER_DISK_CACHE_SKIP_CLEANUP" = "1"
"MESA_GLTHREAD" = "1"
"MVK_CONFIG_FAST_MATH_ENABLED" = "1"
"HARMONY_DEBUG" = "1"

That's copied from the screenshot in the install instructions, as the text field provided only had three options listed. Not sure if this is the way to go since I'm sure I've not installed the Gshade mod.

**Comment by seathasky** [comment]
There is no protocol to follow, you are free to comment on a closed thread. I closed your thread because, our guide, if followed correctly should produce desired results. If you are doing testing or having issues with moltenvk, you have 3 options to use from the install script or you are free to test any of the moltenvks in the public testing section. There isnt much I can do for you outside of that. 

If you installed DXVK 1.9.2, your bottle settings should look like this after first run:
![Screen Shot 2021-11-16 at 7 04 58 PM](https://user-images.githubusercontent.com/17598024/142085575-a13706f7-f90d-40b5-9324-6cf6909fde69.png)

The environment variables to copy are these here:
![Screen Shot 2021-11-16 at 7 07 16 PM](https://user-images.githubusercontent.com/17598024/142085665-f8a975df-881f-4e9f-8d80-0840c2e9b1e2.png)

You dont have to literally copy the screenshot, it's just there as an example.

Best of luck

**Comment by Drunemeton** [comment]
That's perfect. Thank you!
