### ISSUE TITLE
Can't seem to get GShade to install

### ISSUE THREAD

**Issue by FleetAdmiralButter** [seathasky/FF14-MAC_ModSupport#2]
Hi,

I'm coming over from the Reddit thread - I followed the instructions on Step 8 but can't seem to get GShade to install.

I'm at the point where I'm installing GShade.Latest.Installer.exe but the installer throws this error and hangs:

![Screen Shot 2021-10-31 at 10 13 03 pm](https://user-images.githubusercontent.com/37036084/139580217-6d62fc3f-e6df-43dc-bae7-468e587b5d07.png)

My CX is patched using the linked script but I haven't installed XIVLauncher or ACT Parser - I'm not sure if these are required to get GShade to work?

**Comment by seathasky** [comment]
Let me look into this. As of now I need to know if you are on Intel or M1. 

Also if you have all the dependencies installed correctly. 

In the meantime, please try the linux script, it should work on Mac as well: https://github.com/HereInPlainSight/gshade_installer

i just tested in terminal and it seems to be working.
![Screen Shot 2021-10-31 at 7 26 03 AM](https://user-images.githubusercontent.com/17598024/139580781-eea6174f-a6cf-4324-9c90-b22bc299b7ba.png)

**Comment by seathasky** [comment]
Use the linux script, it will work on Mac: https://github.com/HereInPlainSight/gshade_installer

Use option "2" and add it manually.

![68747470733a2f2f692e696d6775722e636f6d2f524c36414d32702e706e67](https://user-images.githubusercontent.com/17598024/139614575-e1be2b49-b5e7-4c6a-9bde-6d4e8575498b.png)

**Comment by FleetAdmiralButter** [comment]
Got it going with the Linux script! Thanks!

**Comment by seathasky** [comment]
Glad it worked!

**Comment by videodromejockey** [comment]
I am having a similar issue but can't install due to apparently missing commands. 

When running the script, I get:

`GShade initial install not found, would you like to create it?  y
Creating...  The following necessary command(s) could not be found: 7z, md5sum, wget, wine
,%`

**Comment by seathasky** [comment]
> I am having a similar issue but can't install due to apparently missing commands.
> 
> When running the script, I get:
> 
> `GShade initial install not found, would you like to create it? y Creating... The following necessary command(s) could not be found: 7z, md5sum, wget, wine ,%`

Unfortunately we only troubleshoot issues related to this project. Your issue is with terminal dependencies. A good place to start is by installing Homebrew for mac and installing missing necessary homebrew (7z, md5sum, wget etc)

https://osxdaily.com/2018/03/07/how-install-homebrew-mac-os/

good luck

**Comment by seathasky** [comment]
@marzent is possibly working on an easier install of Gshade for Mac users. Will update when available.

**Comment by videodromejockey** [comment]
I was able to solve everything but the missing wine command using Homebrew, despite having Wine installed. I would definitely appreciate an easier solution though! Appreciate it.
