### ISSUE TITLE
Planned support for AutoSynthesis? 

### ISSUE THREAD

**Issue by danlavelle** [seathasky/FF14-MAC_ModSupport#20]
I installed AutoSynthesis into my bottle but it unfortunately crashes on startup (logs attached). Any ideas on how to support?
[autosynthesis_crash_log.txt](https://github.com/seathasky/FF14-MAC_ModSupport/files/7548357/autosynthesis_crash_log.txt)

**Comment by seathasky** [comment]
Not on list of things to figure out unfortunately.  I'd contact the author of that addon and figure out what dependencies are needed to run that addon. That would be a good start.
