### ISSUE TITLE
"The program XIVLauncher.exe has encountered a serious problem and needs to close. We sorry for the inconvenience"

### ISSUE THREAD

**Issue by Floki32** [seathasky/FF14-MAC_ModSupport#21]
<img width="1133" alt="Screen Shot 2021-11-16 at 4 00 51 PM" src="https://user-images.githubusercontent.com/38120118/142065563-e4d54578-97e7-48ba-82c2-134271b6187f.png">

I am getting this error every time I try and update the launcher. It get to 58GB and stops.

**Comment by Floki32** [comment]
I am using a windows license and the trial version of crossover. Any help would be much appreciated. THX!

**Comment by seathasky** [comment]
2 possible causes. You are out of hard drive space or you skipped dependacies. Without more information it will be difficult to help.
Show details of error

**Comment by Floki32** [comment]
Hey, how can I check that the dependancies was installed correctly. 

Here is what the show details of error shows: 
 
<img width="875" alt="Screen Shot 2021-11-16 at 4 52 05 PM" src="https://user-images.githubusercontent.com/38120118/142073190-55334bd4-57e4-4cd4-b0d5-8e337fb8f089.png">
<img width="863" alt="Screen Shot 2021-11-16 at 4 52 37 PM" src="https://user-images.githubusercontent.com/38120118/142073203-bf05d9fa-8c6c-4ee9-885f-d62a72b62549.png">
<img width="784" alt="Screen Shot 2021-11-16 at 4 53 03 PM" src="https://user-images.githubusercontent.com/38120118/142073215-62832067-71f9-427e-91e8-e25f04a5c928.png">
<img width="871" alt="Screen Shot 2021-11-16 at 4 56 34 PM" src="https://user-images.githubusercontent.com/38120118/142073224-23281628-933d-43c4-bdc8-bd10fd49abfb.png">
<img width="882" alt="Screen Shot 2021-11-16 at 4 57 45 PM" src="https://user-images.githubusercontent.com/38120118/142073244-bd0e439f-6924-448c-8a2c-2c236701d90a.png">
<img width="805" alt="Screen Shot 2021-11-16 at 4 57 58 PM" src="https://user-images.githubusercontent.com/38120118/142073254-2dd875d3-aff7-48b9-89ea-6f923ae37b3f.png">
<img width="1000" alt="Screen Shot 2021-11-16 at 4 58 36 PM" src="https://user-images.githubusercontent.com/38120118/142073344-ac32b1b9-2506-403c-8307-5fefded7fea6.png">

**Comment by seathasky** [comment]
If you skipped any dependacies or something didn't get installed you will run into issues. My advice would be to run our install script and crosstie again and make sure nothing gets skipped and verify everything gets installed. 

You shouldn't be running into this issue

**Comment by Floki32** [comment]
hmmm.... I don't remember anything not getting installed. But i will try running the script and crosstie again.

**Comment by Floki32** [comment]
UPDATE: So I deleted the bottle, and restarted from step one. So far the launcher hasn't ran into any errors. IDK what happened, but I didn't do anything different this time... 

Unfortunately the update is pretty big, and i have slow internet, so i have to wait a while for it to finish the download.

**Comment by seathasky** [comment]
Let me know how it goes! Good luck! Closing this issue for now

**Comment by Floki32** [comment]
UPDATE: After 8+ hrs, it finally finish the download. I did run into the issue 2 more times. I'm thinking it may just be related to my internet connection, and not due to me missing something during the install. 

But I was able to force close the launcher and restart the download and eventually finished.
