### ISSUE TITLE
Add a warning when changing MoltenVK

### ISSUE THREAD

**Issue by Gcenx** [seathasky/FF14-MAC_ModSupport#22]
Changing MoltenVK may benefit FF however other applications/games will be affected negatively. (e.g. Witcher3 only like MoltenVK-CX-21 on Apple Silicon)

Another important thing that should be noted is changing any files within CrossOver.app breaks Code-Signing and Notarization meaning some required entitlement requests will become invalid and ignored. (e.g. macOS Catalina 10.15.0 > 10.15.3 might fail to load 32Bit Windows binaries after this)

And the obligatory\
”Using custom MoltenVK/DXVK packages will render any feedback to CodeWeavers invalid and you won’t be provided any support for this configuration by CodeWeavers”

All the above applies double when swapping out files to enable using a Windows license to play FF on macOS.

**Comment by seathasky** [comment]
I can update the public testing page with this information for sure. I think most people will mainly be using your compiles for this project but the information is useful regardless. Honestly just going to screen this if you're okay with that so it's coming from you yourself.

**Comment by seathasky** [comment]
Public testing now includes your warning, Thanks Dean!

![Screen Shot 2021-11-17 at 11 01 17 AM](https://user-images.githubusercontent.com/17598024/142235884-bb22c527-f407-4b0c-b1b9-948ea8b80166.png)
