### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by supasubu** [seathasky/FF14-MAC_ModSupport#26]
Hi there!

I am running an M1 Max Macbook Pro, and encountered an error when running through the installation. Currently, there are 3 files "in process", while the file "Microsoft .NET Framework 2.0" would not install, giving me an error message. I chose to "skip" the installation after several "try again" attempts. Will this mod function properly without it?

If not, what are my troubleshooting steps? It's a new machine, so today I also wiped the entire hard drive to start fresh, only to find the same error from my previous attempt. Thanks all for any suggestions! (FYI I chose option 2 when running the "install.command")

**Comment by RussellAnas** [comment]
Following

**Comment by seathasky** [comment]
repeat issue: 
https://github.com/seathasky/FF14-MAC_ModSupport/issues/24
https://github.com/seathasky/FF14-MAC_ModSupport/issues/17
check these first
