### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by crowcold** [seathasky/FF14-MAC_ModSupport#28]
Hello, 
I tried installing the ffxiv Mac cross over, firstly I just wanted to ask some question. I am new to this whole thing so I am not sure what this does. Do I have to buy the Mac version of FFXIV to use this? I tried installing it previously but it said It said "this square enix account cannot play final fantasy".  I then spoke to somewhen on discord and they mentioned "ntdll patch". I have no idea what to do. Please if you can give me a simplified direction as to how to make this work on my Mac book, it will be greatly appreciated.

**Comment by seathasky** [comment]
responded to you on discord.
