### ISSUE TITLE
Support AMD Hackintoshes by custom solution / guide

### ISSUE THREAD

**Issue by memegauste** [seathasky/FF14-MAC_ModSupport#29]
So, the AMD Hackintoshes lacks somewhere ability for 32-bit code execution, and because of this the 32-bit parts of CrossOver are not working (it just crashes). Despite that, FF XIV native macOS client is running just fine, so it probably uses ONLY 64-bit code.

So, when you want to use `FF14-MAC_ModSupport` it will crash at same beginning of modding the client, because fonts installer in Windows are 32-bit based. I would really appreciate writing script/describing method that overrides current FF XIV client e.g. updating MoltenVK & CrossOver parts without the need to mess with CrossOver at all.

https://github.com/AMD-OSX/bugtracker/issues/6

**Comment by seathasky** [comment]
Not sure you were asking me to write you a guide or you wanted to write one. either way, here is how:

---

Find your "FINAL FANTASY XIV ONLINE" folder. By default, Square Enix's installer should put it in Users/USERNAME/Library/Application Support/ 
![Screen Shot 2021-11-24 at 3 13 16 AM](https://user-images.githubusercontent.com/17598024/143199933-097ea672-032d-419f-b881-b4c18c472ede.png)

(if you cant find the library folder, press cmd + shift + [.] to show hidden folders while in the user directory)

When you get in the directory, it should look like this: 

![Screen Shot 2021-11-24 at 3 15 05 AM](https://user-images.githubusercontent.com/17598024/143200145-0187d20e-8d1a-433b-a7e4-6ab481c75b1f.png)

Download the latest DXVK release from https://github.com/marzent/dxvk/releases
unzip the folder, you should see a dxvk .dlls. use the x64 ones
![Screen Shot 2021-11-24 at 3 17 10 AM](https://user-images.githubusercontent.com/17598024/143200503-2dccf171-70ed-46c7-b722-b6fa94712a46.png)

Open "windows/system32 and copy and overwrite the dlls into that folder.
That will update dxvk.

---

**For moltenvk,** 

right click and show package contents on  the FFXIV app in your applications folder
![Screen Shot 2021-11-24 at 3 19 43 AM](https://user-images.githubusercontent.com/17598024/143200859-df9969da-50d8-4a17-876b-8ddce00db177.png)

Open contents and locate the lib64 folder here:
![Screen Shot 2021-11-24 at 3 21 24 AM](https://user-images.githubusercontent.com/17598024/143201059-ca039998-d242-4c45-8223-a1b535a347e2.png)

Unzip the latest macos_dxvk_patched.tar.xz from the releases here: https://github.com/Gcenx/MoltenVK/releases

![Screen Shot 2021-11-24 at 3 23 19 AM](https://user-images.githubusercontent.com/17598024/143201270-98bae103-aaea-42c4-a132-1ccbdff8e1be.png)

copy and overwrite the libMoltenVK.dylib into the lib64 folder.

Profit.

Good luck!

**Comment by memegauste** [comment]
I were asking you to write the guide. Anyway, thanks very much! I will respond today how much performance improved on my AMD Hack.

I don't close issue for now without testing if that works.

I want to ask another question, does performance differ from CrossOver releases? I know that FF XIV ShadowBringers is based on CX20.

**Comment by seathasky** [comment]
Yes, the performance should be different in cx21 due to wine also being updated in Crossover.
You will most likely have a better experience through Crossover but this should help the default client a little bit either way
