### ISSUE TITLE
Unable to login with Windows license

### ISSUE THREAD

**Issue by Jaybotics** [seathasky/FF14-MAC_ModSupport#3]
Hello, I did all the steps on here, and I have done the regedit, the game loads perfectly fine, but when I select my datacenter to login it gives me an error message saying that this service license isn't registered to this account.

<img width="1289" alt="Screen Shot 2021-10-31 at 6 15 13 AM" src="https://user-images.githubusercontent.com/93477207/139585275-0e2b32c3-b50c-42ae-bcf5-a3c676c8a279.png">

**Comment by seathasky** [comment]
https://github.com/marzent/ffxiv-on-mac did you run this script first? This will patch your Crossover and allow HideWineExports to function properly.

**Comment by Jaybotics** [comment]
I didnt, but did just now and still having the issue with logging in. Do I need to redo the whole process?

**Comment by seathasky** [comment]
Are you using stock launcher or xivlauncher? 

Also if you patched your Crossover correctly you will only be able to log into a windows license by default unless you add 0 to hidewineexports. Make sure the script was successfully installed

**Comment by Jaybotics** [comment]
I just downloaded Crossover a few days ago, so unless their was an update in the last couple of days, it should be the most current version. I can check later. I'm also using XIVLauncher. How can I tell if the script was successfully installed?

**Comment by seathasky** [comment]
Xivlauncher should say "wine on linux" in the title.
![68747470733a2f2f692e696d6775722e636f6d2f796b77664c706d2e706e67](https://user-images.githubusercontent.com/17598024/139613889-deec783d-ea36-48a9-b900-9393b54e4b53.png)


After installing Marzent's script correctly, terminal will echo 'You can now follow the rest of the install guide!'

**Comment by seathasky** [comment]
Assuming you got this working due to lack of response. closing ticket
