### ISSUE TITLE
Problem installing

### ISSUE THREAD

**Issue by ysimard94** [seathasky/FF14-MAC_ModSupport#30]
Hi! When I try to install everything, when it comes to the .NET Framework 4.0, 4.6.2, 4.7.2 and 4.8, it says "Setup may not run properly, because the Windows Modules Installer Service is not available on this computer." and then stops forever at 5 bars in the installation process of each and single one. My process is install crossover, then opening  the FFXIV installation file like in the first step says. Is there a step that I'm missing? I own an M1 MacBook Air on Monterey. Thanks!

**Comment by seathasky** [comment]
https://github.com/seathasky/FF14-MAC_ModSupport/issues/17
