### ISSUE TITLE
Character/Client Settings Migration

### ISSUE THREAD

**Issue by RussellAnas** [seathasky/FF14-MAC_ModSupport#31]
Hi, is it possible to download my character/client settings from the online FF14 backup/restore tool to this crossover version with the different launcher? Or will it corrupt the settings?

Otherwise, I'll have to setup everything from scratch like macros, hotbars and that would be a pain.

**Comment by seathasky** [comment]
Hi there Russell. 
Your character and client settings are stored on Square Enix's servers. There is no difference between the client's being used in CX vs Mac, Windows 10 and even PS4/PS5. Your client settings are cross platform enabled and you will not have any issues at all.

Use the in-game Character/Client backup feature and you'll be fine!

![Screen Shot 2021-11-27 at 5 09 34 AM](https://user-images.githubusercontent.com/17598024/143677073-8dc62e3b-7688-4cb7-b67c-aec775a85407.png)

Hope this helped!

**Comment by RussellAnas** [comment]
This definitely helps! Thanks @seathasky!
