### ISSUE TITLE
Stuttering on 16" M1 Max

### ISSUE THREAD

**Issue by RussellAnas** [seathasky/FF14-MAC_ModSupport#33]
Hi, so I am using DXVK 1.9.2 and MoltenVK 1.1.6. My game is still occasionally stuttering.

FPS is high (around 70-80), but suddenly it stutters (including the sound), so it seems like the whole game gets stuck. I'm not using any special plugins yet, only show the fps on the screen.

I did download my character/client settings. But then I did adjust the graphics preset to 'High Laptop' and also tried 'Standard Laptop' (both with HBAO turned off). 

Just an fyi that I'm playing on an external 1080p 240hz monitor. Tried both fullscreen and windowed and it stutters.

Can you guys help? Is this expected or only happening with me?

**Comment by seathasky** [comment]
Hi Russell.
   Which compile of MVK did you use? 
From our script or from public testing (Gcenx or FleetAdmiralButter's compile)?

When you say stuttering, do you mean screen tearing, or fps drops? Did you allow shader cache to compile? It usually takes a bit on first run.

Have you tried using MvK 1.1.4? It's what we recommend for M1 users.

**Comment by RussellAnas** [comment]
I'm actually using FleetAdmiral's compile for 1.1.6.

I mean clear stuttering, not tearing or fps drop. The whole game pauses for a second or so now and then. When it runs, it runs good. But this keeps happening every 4-5 minutes. 

Should I go back to 1.1.4? Any idea how I can get the 1.1.4 version?

**Comment by seathasky** [comment]
Either use our script again (skip crosstie when it prompts) or the 1.1.4 tag in public testing on Gcenx's compiles. Public testing is just that, for testing. 

Our script tells you this:
![Screen Shot 2021-11-27 at 10 26 46 AM](https://user-images.githubusercontent.com/17598024/143687290-4587c0d2-04b9-432b-9e79-fff55d06c76d.png)

**Comment by RussellAnas** [comment]
These are the options I see, which one should I go for? Don't see an option for 1.1.4

![Screen Shot 2021-11-27 at 8 36 07 PM](https://user-images.githubusercontent.com/77004545/143687612-ccf3b63a-a993-43b5-9de6-cbafb759c42e.png)

**Comment by seathasky** [comment]
Gimme a sec, ill update the script to include 1.1.4

**Comment by seathasky** [comment]
Okay re-download/clone, the scipt is updated and should include 1.1.4. Let me know if it doesnt

**Comment by RussellAnas** [comment]
YOU WERE RIGHT! It's working perfect now with 1.1.4! OMG I thought I upgraded to the M1 Max GPU for nothing!

**Comment by seathasky** [comment]
Glad it's working!

**Comment by kayzerkan** [comment]
Just to be safe: The 1.1.4 version was added after I cloned the repository and I am encountering the same problem on my m1 macbook pro.

When I execute the install.command and pick the 1.1.4 option, I don't have to reinstall the bottle again? Because I don't want to wait for another 60 gb download :D

**Comment by seathasky** [comment]
The 1.1.4 version has been in the script pretty much since we made it, but we removed just 2 days ago to have M1 users move to 1.1.6. I went ahead and re-added it, as 1.1.6 is still technically in testing.

Just re-clone/download the repo and rerun the script and skip the crosstie
