### ISSUE TITLE
DXVK Backend gets unchecked

### ISSUE THREAD

**Issue by RussellAnas** [seathasky/FF14-MAC_ModSupport#34]
Quick question (sorry for making so many of these). Once I upgrade DXVK using your guide, the checkbox automatically gets unchecked on my bottle (even though I clearly remember checking it before). Is this expected once we replace the DXVK file to 1.9.2?

**Comment by seathasky** [comment]
This is normal behavior. If you re-check it, it will revert to default dxvk. Leave it unchecked after you overwrite.

I updated the guide to reflect this for new users going forward
