### ISSUE TITLE
FFXIV not detecting Windows licence after changing HidewineExports to 1

### ISSUE THREAD

**Issue by RoyalRookie** [seathasky/FF14-MAC_ModSupport#36]
It's still detecting the MacOS version and I don't know how to fix this.

**Comment by ghost** [comment]
I don't know if it's case-sensitive or not; have you tried "HideWineExports" or "HidewineExports"?

**Comment by seathasky** [comment]
If you patched for windows using our script you should not have an issue. Repatch with the script and try again.
