### ISSUE TITLE
Alternatives to BunnyHud

### ISSUE THREAD

**Issue by RussellAnas** [seathasky/FF14-MAC_ModSupport#37]
Hi - considering there's some bug that is causing issues with BunnyHud too, is there any alternative to showing ACT's Kagerou layout somehow? I see ACT is successfully getting all the data, but doesn't show up on BunnyHud.

**Comment by seathasky** [comment]
You can use act's Websocket feature to use Kagerou in Chrome web browser, just add the address from the websocket section in ACT

**Comment by RussellAnas** [comment]
I've never done this before so apologies in advance, what should I do next to see Kagerou in chrome?
![Screen Shot 2021-11-29 at 2 50 16 PM](https://user-images.githubusercontent.com/77004545/143845673-368bdc67-b130-4b5f-8945-4f26acf37936.png)

**Comment by seathasky** [comment]
Generate a url at the bottom, profit

**Comment by RussellAnas** [comment]
Okay I get what was the issue here. It showed me nothing in overlay. I had to go and add kagerou using the usual process first, and then I could see various options in overlay here under url generator!
