### ISSUE TITLE
Patch Installer issue when trying to install to external drive 

### ISSUE THREAD

**Issue by EddDaDing** [seathasky/FF14-MAC_ModSupport#4]
![Screen Shot 2021-11-01 at 9 17 58 pm](https://user-images.githubusercontent.com/93520369/139656762-39491605-e079-40f9-9604-1e3109db6992.png)

When I try to install via the portable launcher I get the Error shown in the print screen, trying to install to external drive as not enough room on m1 Mac mini drive. 

When I try and run the regular launcher it just pauses on this screen (screenshot below). Not really sure where to go from here.

I doubt I could use the official launcher anyway as I need to use the steam work around.

Any advice would be appreciated, thanks.

![Screen Shot 2021-11-01 at 9 19 41 pm](https://user-images.githubusercontent.com/93520369/139656998-d3efcd69-3534-4f63-b100-28f5b33e2c4d.png)

**Comment by EddDaDing** [comment]
![Screen Shot 2021-11-01 at 10 58 58 pm](https://user-images.githubusercontent.com/93520369/139668077-8af79770-98c2-4c75-b5d4-9f8132b908a0.png)

Now I don't know how but I have regressed to this, can't even get the launcher open...

**Comment by seathasky** [comment]
I'm looking into the XIVLauncher for you with the devs but I would change your patching method to ARIA. It's probably set to NET.
![Screen Shot 2021-11-01 at 8 44 58 AM](https://user-images.githubusercontent.com/17598024/139673537-febc5965-f868-44a1-8163-a59e95aab1a3.png)
Alternatively, run the 2nd way of installing Xivlauncher, make sure to uninstall any trace of xivlauncher prior (including anything in your app data folders)

As far as default launcher, at the very bottom of the guide their is a fix for that.  
Open FFXIV_BOOT.cfg and change these settings "Browser = 1"

I updated the guide in the troubleshooting section if you need more help with the default launcher.

**Comment by EddDaDing** [comment]
Thanks for the timely response I will give it a go tomorrow, as for the removing every trace of the old launchers is there a step by step I can follow somewhere to do that?

**Comment by seathasky** [comment]
> Thanks for the timely response I will give it a go tomorrow, as for the removing every trace of the old launchers is there a step by step I can follow somewhere to do that?

You're very welcome. As far as removing every trace. Remove the initial folder you downloaded completely and then go to your users folder and find the folder xivlauncher as well: 
![Screen Shot 2021-11-01 at 9 43 41 AM](https://user-images.githubusercontent.com/17598024/139681330-b4fe42df-7403-4aff-a98f-4887e12fb1a2.png)

just delete that, start over and make sure to set patching to aria 👍

**Comment by EddDaDing** [comment]
![Screen Shot 2021-11-02 at 4 50 42 pm](https://user-images.githubusercontent.com/93520369/139793300-e4a4ee66-18a2-4435-94f7-a9f201a40ac3.png)

Deleted all the folders and re ran the launcher and am now getting this before I can try logging in with the new settings.

**Comment by seathasky** [comment]
is .net 4.8 installed? if not https://support.microsoft.com/en-us/topic/microsoft-net-framework-4-8-offline-installer-for-windows-9d23f658-3b97-68ab-d013-aa3c3e7495e0 also which install did you do?

**Comment by EddDaDing** [comment]
yes .net 4.8 is installed and I selected run command and opened the launcher

**Comment by seathasky** [comment]
which file are you trying to launch? Screenshot the exact folder structure

**Comment by EddDaDing** [comment]
![Screen Shot 2021-11-02 at 5 04 17 pm](https://user-images.githubusercontent.com/93520369/139794452-38f3b31d-2942-42d5-8699-03b5747b15b8.png)

**Comment by EddDaDing** [comment]
the second I try to type in the password field and freezes and crashes

**Comment by seathasky** [comment]
Do me a favor and open crossover and show me all the dependencies you have installed. scroll down and show screenshot for everything if you can
![Screen Shot 2021-11-02 at 2 10 29 AM](https://user-images.githubusercontent.com/17598024/139795155-4000cfca-8218-4ca7-861f-a76375af8a16.png)
:

**Comment by EddDaDing** [comment]
![Screen Shot 2021-11-02 at 5 14 59 pm](https://user-images.githubusercontent.com/93520369/139795470-96f3bc85-f77d-49aa-a809-7f0614819371.png
![Screen Shot 2021-11-02 at 5 15 09 pm](https://user-images.githubusercontent.c
![Screen Shot 2021-11-02 at 5 15 20 pm](https://user-images.githubusercontent.com/93520369/1397
![Screen Shot 2021-11-02 at 5 15 27 pm](https://user-images.githubusercontent.com/93520369/139795529-f138c03f-849d-48bb-bdaa-3498ac23f139.png)
95514-f21a9545-58be-40a6-9d57-92819b54e3a6.png)
om/93520369/139795491-d2914b48-3464-4123-85fc-933d7431778d.png)
)

**Comment by EddDaDing** [comment]
![Screen Shot 2021-11-02 at 5 16 30 pm](https://user-images.githubusercontent.com/93520369/139795630-e590dd42-2579-436d-9ecf-8fd8e8b880fa.png)

![Screen Shot 2021-11-02 at 5 16 47 pm](https://user-images.githubusercontent.com/93520369/139795656-13987ef2-a820-47c0-9ed0-73307791eac6.png)


![Screen Shot 2021-11-02 at 5 17 03 pm](https://user-images.githubusercontent.com/93520369/139795686-97a936ac-5bde-4aa9-9d7b-acdecf2d1e05.png)



![Screen Shot 2021-11-02 at 5 17 15 pm](https://user-images.githubusercontent.com/93520369/139795705-adb91d83-48b8-4832-ba0d-774d05fc212b.png)

**Comment by seathasky** [comment]
you are missing key .net frameworks from the x64 dependencies, did you get errors when making your bottle?

**Comment by EddDaDing** [comment]
It got stuck a bunch of times and I had to press skip it was either skip or cancel

**Comment by seathasky** [comment]
You need to redo your bottle completely, if you follow the guide step by step, you shouldn't have issues. That is my recommendation. just move your square enix folder from that bottle to your desktop, and stick it into the bottle if you already downloaded the full game (to save you time)

If anything gets skipped, you will run into these issues again

**Comment by EddDaDing** [comment]
Ok I will try from scratch now and let you know if the error come up again

**Comment by seathasky** [comment]
Screen shot any errors while installing (if you get any).

**Comment by EddDaDing** [comment]
![Screen Shot 2021-11-02 at 6 10 47 pm](https://user-images.githubusercontent.com/93520369/139801522-4e4481cf-d0a5-4059-8abf-6ea8e77c9ee7.png)

!new error just dropped!

getting closer it seems at least.

**Comment by EddDaDing** [comment]
![Screen Shot 2021-11-02 at 6 15 29 pm](https://user-images.githubusercontent.com/93520369/139802061-167d7ebc-0a28-46cd-823a-1bf280755724.png)

tried again and got this

**Comment by EddDaDing** [comment]
Maybe I can't install from scratch in a wine bottle to a external drive? I unfortunately have no space to install it onto the Mac drive and move it over.

**Comment by EddDaDing** [comment]
![Screen Shot 2021-11-02 at 6 45 49 pm](https://user-images.githubusercontent.com/93520369/139805883-54d27958-d349-40ba-8966-7d485a9c065e.png)

When I try and run the default launcher using the fix you posted earlier, changing the config file browser to "1".

**Comment by seathasky** [comment]
Not sure why xivlauncher is giving you soo much trouble, that's odd. As far as default launcher, press enter while in pw field instead of pressing the button with mouse. This is covered in the troubleshooting section:

![Screenshot_20211102-073355_GitHub.jpg](https://user-images.githubusercontent.com/17598024/139839117-2111e920-d798-4502-bf77-fd4a7acad764.jpg)

I don't know how to help with xivlauncher at this point, this guide is fool proof and has been tested to work by a lot of people.The only difference is we did it on our main drives. I can't really troubleshoot beyond this point but I would free up space on your main drive and try there. Only other option I can think of is try Mazents crosstie he has on his page or post in the xivlauncher discord. Google goats place discord

**Comment by EddDaDing** [comment]
The default launcher was crashing before I even got to that point that screenshot was on opening the client. As for the rest of the issues I have managed to make space despite my crying and Im just installing onto the Mac HDD which now has it downloading so I assume has fixed the Issue.

So there is definitely some issue with trying to use crossover to download and install the game straight onto an external.

**Comment by seathasky** [comment]
It might have been a FF14 thing/crossover on external like you said. That's why I was confused why it wasnt working for you. Either way, this is good bug testing and I will use this information in the guide that you cant run cx on an external hd.

You can most likely symlink your install after everything is setup if you need the extra space. You can read about symlinking here if you have never done it: https://www.howtogeek.com/297721/how-to-create-and-use-symbolic-links-aka-symlinks-on-a-mac/

**Comment by EddDaDing** [comment]
Cheers will let you know and if I had to guess its probably due to some macOS secret permissions stuff. Since like bigsur permissions have gotten way more strict and just allowing it in the privacy/security tab doesn't give it full access you have to constantly select "allow".  I feel like since its a virtual app being emulated the permissions to allow it access to the external aren't sticking or something.

**Comment by EddDaDing** [comment]
![Screen Shot 2021-11-03 at 12 02 58 am](https://user-images.githubusercontent.com/93520369/139851921-a6e19263-da49-411f-b08f-2a2d7d16fb98.png)

ok so, made it this far and now have infinite loading screen after choosing data centre. I don't think this is the infinite black screen bug you mentioned in the troubleshoot section right? because that was a completely black screen for cinematic where as has the loading wheel spinning in the bottom.

**Comment by EddDaDing** [comment]
![Screen Shot 2021-11-03 at 12 58 19 am](https://user-images.githubusercontent.com/93520369/139861552-0f3919ec-107d-4413-b195-06b132d5ed75.png)

Ok well I finally made it in after all that. Thanks for all the advice along the way, currently running on a 8gig ram m1 Mac mini so nothing too impressive to show for it yet but if I can replicate the installation onto my m1 max when it arrives should be smooth sailing. Thanks again.

**Comment by seathasky** [comment]
Happy you got it working! You should get way better performance on the M1 Max!

I added the external harddrive stuff to the troubleshooting section for those trying to do it in the future. Again, you should be able to symlink to your external if you choose to.

**Comment by seathasky** [comment]
Oh, forgot to mention, we overhauled the guide to include crosstie install as default, so when you get your new Mac, try that method, should be way easier!
