### ISSUE TITLE
m1 max can not success install the launcher with cx21

### ISSUE THREAD

**Issue by Lalumieree** [seathasky/FF14-MAC_ModSupport#40]
new 16-inch mbp using crossover21.1 can not install .net framework, which leads to the launcher fail to lunch( which said need the 4.72 .net framework, the offline package doesn't work)

**Comment by seathasky** [comment]
Please read "Step 1" again carefully before posting existing issues
![Screen Shot 2021-11-29 at 11 54 16 AM](https://user-images.githubusercontent.com/17598024/143909931-62fdc78c-c0b3-451a-a90a-c0869f173507.png)

If you still can not install dependencies, contact Codeweavers. We have no control over their software.

**Comment by Lalumieree** [comment]
yep, I checked the issue17 and follow the steps, still met failure. Thanks anyway.

**Comment by seathasky** [comment]
I'm sorry it is not working for you. That can be frustrating I'm sure!

I'd recommend first restarting completely over, make a new bottle, start from scratch.

If you still can not get it working, i'd contact Codeweavers. 

Best of luck
