### ISSUE TITLE
FFXIV not detecting expansions

### ISSUE THREAD

**Issue by RoyalRookie** [seathasky/FF14-MAC_ModSupport#42]
FFXIVLauncher does not detect anything missing and I have the expansions installed, but when I boot up FFXIV it doesn't have stormblood/shadowbringers

**Comment by RoyalRookie** [comment]
It worked at first and I don't know what changed

**Comment by seathasky** [comment]
Windows or Mac license?

**Comment by RoyalRookie** [comment]
windows

**Comment by RoyalRookie** [comment]
already changed the value to 1

**Comment by seathasky** [comment]
Your game not showing current expansions has nothing to do with our installation or xivlauncher for that matter. That has never been a thing.

Also when you say your game doesnt have SB/ShB, do you mean you cant go to those zones?

Are you sure you have an active account? Or are you on a trial?

**Comment by RoyalRookie** [comment]
I have an active windows account. I downloaded all the expansions and it worked at first, but now I logged out at a Stormblood area and the game says I have to install Stormblood to log in. I did try to run the endwalker benchmark and the original launcher in the same bottle so maybe that's why it doesn't work anymore? I guess I can make a new bottle with a new installation..

**Comment by seathasky** [comment]
As I stated before, account issues have nothing to do with XIVLauncher.

Do you happen to have any Mac licenses at all on your account?

I can see the scenario where you didn't patch for windows correctly and wine is only seeing your Mac license. 

When you run Xivlauncher, does the title say "wine on mac" or "wine on linux" at the top?

**Comment by RoyalRookie** [comment]
XIVLauncher says wine on mac, but I did patch for windows correctly because it worked before.

**Comment by RoyalRookie** [comment]
I don't have mac licences

**Comment by seathasky** [comment]
Redo your bottle. For accuracy, do step 1, step 2 and step 7. Make sure when you patch, you say "Y" for windows license. You should not have any issues. Do not install XIVLauncher with the xivlauncher.exe included in the patcher zip, this is for mac users only.

Best of luck
