### ISSUE TITLE
Immerse Gamepack compatibility discussion

### ISSUE THREAD

**Issue by ghost** [seathasky/FF14-MAC_ModSupport#43]
Some tips from me:

- In case your `Microsoft Edge WebView2 Runtime` installation fails, try the newest version from the Microsoft's [website](https://developer.microsoft.com/en-us/microsoft-edge/webview2/).
- To run the Immerse application you'll need to copy `tbs.dll` from the newest package of linux [Wine](https://archlinux.org/packages/multilib/x86_64/wine-staging/) to your `Windows/system32` folder.

Haven't managed to run it in-game yet, it probably requires Windows license and I have no idea whether this has any right to work.

**Comment by seathasky** [comment]
I dont own it, and either do my colleagues yet. It may be hard to maintain this if one of us do not purchase. 

I work with audio for a living, so anything to enhance the game with audio is appealing to me. I will look at some reviews of this and decide if we will support this or not.

Either way, thank you for submission. I'll discuss this with the team.
