### ISSUE TITLE
Alternate CrossOver movie fix (working movies)

### ISSUE THREAD

**Issue by reckenrode** [seathasky/FF14-MAC_ModSupport#44]
I’ve been running FF XIV under CrossOver 21 for the performance improvements, but I’ve been wondering why the movies don’t work under CrossOver (and vanilla WINE) when they _do_ work on the official Mac client. It turns out the Mac client includes Bink-encoded versions of the movies that aren’t included with the Windows client. If you copy them into movies folder of the Windows client, they work. I expect this also holds true for Proton/WINE under Linux, but I haven’t tested it.

The process just involves downloading the Mac client from https://mac-dl.ffxiv.com/cw/finalfantasyxiv-1.0.5.zip, extracting the movies from it, and copying them into your bottle. I was able to confirm it works by resetting `CutsceneMovieOpening` to `0`, trying to connect to a data center, watching the opening video with Hydaelyn, and then seeing character select screen once it finished.

I put together a shell script to automate downloading the client and extracting the movies to a bottle. It’s available [here in a gist][1].

[1]: https://gist.github.com/reckenrode/20dd7523309bfaa981fea9b6ec3aa687

**Comment by seathasky** [comment]
Oh wonderful! This is valuable information.

 I have not yet looked at your script but does this require the full installation of the game to run? If so, would it be possible to just exclude all other files? Or did I incorrectly read what you meant.

Either way, this is something we could implement in the future, as an option of course.

**Comment by reckenrode** [comment]
The files are included in the zip as part of the app bundle, so a full installation isn’t necessary (which would just symlink to the files in the app bundle anyway). My script just grabs the zip, extracts the four movie files from it, and copies them into place.

**Comment by seathasky** [comment]
That's a neat trick. So no need for the cutscene fix. I will have to test this tomorrow as it's getting late, but this would be a great addition to our current script. You should join us in our discord so we can discuss it more.

**Comment by marzent** [comment]
So I did some testing and while it does alleviate the arr cutscene issues it also causes Dalamud staging to fail injection atm, once Dalamud is able to handle the different memory offsets and you are fine with it we can add it to the guide though!

**Comment by reckenrode** [comment]
Adding it to the guide would be totally fine. That’s why I made sure to include the MIT license block at the top of the script.

**Comment by marzent** [comment]
Actually I've had kinda random behaviour concerning Dalamud, I thought it was the blink video at first but now I'm not so sure anymore, will have to do some more testing on this

**Comment by reckenrode** [comment]
> That's a neat trick. So no need for the cutscene fix. I will have to test this tomorrow as it's getting late, but this would be a great addition to our current script. You should join us in our discord so we can discuss it more.

Sure, I hopped on the Discord.

**Comment by reckenrode** [comment]
@marzent Should I open a PR against marzent/ffxiv-on-mac, or is this outside the scope of your repo?

**Comment by marzent** [comment]
Feel free to open a PR, am currently working more on the standalone wrapper but that doesn’t mean the CX patcher should be neglected ;)

As a small addition your script currently doesn’t handle non standard install locations very well, maybe it’s better to give it a game folder as argument in case it can’t find a Bottle

**Comment by seathasky** [comment]
~~Use the discord #development channel and ping Marzent~~
Nevermind 😁
