### ISSUE TITLE
Unable to get ACT working

### ISSUE THREAD

**Issue by Rydsmith** [seathasky/FF14-MAC_ModSupport#45]
Since ACT updated I haven't been able to get it to work. The "Use WinPCAP-compatible library" option is selected but I continue to get "Failure: PCAP is selected but no data received."

I have Wireshark installed and running and the network is obviously coming through on it but ACT continues to give errors.

**Comment by seathasky** [comment]
Hey Ryd. Just tested myself and it ACT is working. 
![Screen Shot 2021-12-07 at 10 25 26 PM](https://user-images.githubusercontent.com/17598024/145143210-c3acbe9a-bcd3-4557-9322-38c0fd285eb1.png)

Is this your first time installing it? Or were you using it Shadowlands with our install guide?

**Comment by Rydsmith** [comment]
I used it with Shadowlands without issue before using your guide.

**Comment by seathasky** [comment]
It's hard to diagnose your issue as nothing has really changed from Shadowbringers to Endwalker in terms of ACT. Hence why it should be working flawlessly as long as you didnt do anything different besides update the software. 

The ACT Plugin still functions the same regardless of it being visually different:
![Screen Shot 2021-12-07 at 10 33 12 PM](https://user-images.githubusercontent.com/17598024/145143729-cf2e17f3-d179-4f98-a93a-e6c4532499c0.png)

My advice would be to reinstall wireshark through our script. Restart your Mac, and try again. As long as ACT is in the same bottle as FF14 you should not have any issues.

**Comment by Rydsmith** [comment]
Alrighty, thank you. I'll give this a shot tomorrow (just because of queues right now; don't want to leave when I managed to get in heh).

**Comment by seathasky** [comment]
I totally understand your frustration, I actually just crashed 30 minutes ago and got stuck in a 4000 queue. 

I'd advice you to join our Discord, you will get faster support there in the future.

**Comment by seathasky** [comment]
After more extensive testing, ACT is 100% working with all the latest updates and BunnyHUD in Endwalker.

![Screen Shot 2021-12-07 at 11 47 19 PM](https://user-images.githubusercontent.com/17598024/145149973-d350c8e3-dee5-4439-a99c-05f43403ebc2.png)

Please make sure you have configured ACT accordingly. 
Double check to see if FFXIV Process ID is available, and manually set Local IP to 127.0.01
You said you had wincap selected already so keep that as is.

![Screen Shot 2021-12-07 at 11 48 50 PM](https://user-images.githubusercontent.com/17598024/145150045-4dbedd02-73de-4e49-89f5-bca827767e82.png)

After that make sure you have Stream/Local Overlay started and status shows: **Running**

![Screen Shot 2021-12-07 at 11 50 03 PM](https://user-images.githubusercontent.com/17598024/145150129-3e403950-4063-4c05-8c72-e74cd500b466.png)

Best of luck!
