### ISSUE TITLE
Add information that Endwalker expansion also needs patching if you want to get performance benefits

### ISSUE THREAD

**Issue by memegauste** [seathasky/FF14-MAC_ModSupport#46]
Hello,
So I asked CodeWeavers if they updated FF XIV macOS port internals and I got this answer:

```
Hi there,

No, there were no updates to anything on our end: the expansion worked without needing any development from CodeWeavers. And in general, the decision to update Wine, DXVK and/or MoltenVK is really up to Square Enix: we're in regular talks with them about potential updates, but it's ultimately up to them.

Best,
Meredith
```

So I think it would be nice to mention about this in README of this project.

**Comment by seathasky** [comment]
I mean it goes without saying, the entire drive behind this project was the lack of updates to Squares Enix's (Bottle/Native Launcher)
