### ISSUE TITLE
Stuck on loading screen

### ISSUE THREAD

**Issue by RoastTuna** [seathasky/FF14-MAC_ModSupport#47]
I am on M1 macbook pro 14. 
The game launches but gets stuck after i select the datacenter.
stuck in the blank loading screen indefinitely 
<img width="1392" alt="Untitled" src="https://user-images.githubusercontent.com/96094523/145918085-dd885c4a-bfc7-4733-88f4-4233fdc64389.png">

**Comment by seathasky** [comment]
Go to troubleshooting
