### ISSUE TITLE
Game stuck loading data center

### ISSUE THREAD

**Issue by front-endian** [seathasky/FF14-MAC_ModSupport#49]
I went through all the steps in your guide successfully (thanks for putting together this guide!), and the game launches. However, when I hit "Start" in game it asks me to select a datacenter, then says it is connecting to datacenter, and then I am brought to a black loading screen with a spinner in the bottom right corner. It ends up stuck here endlessly.

M1 Max system running Monterey 12.1

Let me know if there is any additional info I can provide you to help debug this.

**Comment by seathasky** [comment]
https://github.com/seathasky/FF14-MAC_ModSupport#troubleshooting

**Comment by front-endian** [comment]
Thank you! I was dumb and skipped over that step because it wasn't entering a cutscene. Fixed that issue perfectly.
