### ISSUE TITLE
Game launches but can’t get past start menu

### ISSUE THREAD

**Issue by Graendhal** [seathasky/FF14-MAC_ModSupport#50]
First of all, thank you for your work on this. See this is what tipped the scale and made me buy a MacBook Pro rather than hold off for a windows laptop.

Second, I am following your guide, but ran into an issue. I have tried following it to the tee, but I am new on macOS so perhaps there was user error on my end. I have followed all the steps (I think) up to Step 3 where we install ACT and specifically the part where we "Test Game Connection" by loading up the game and running that test within ACT.

I can get to the opening screen of FFXIV just fine, but when I hit Start, it takes me to a screen that asks me to choose my Data Center, which is weird since I already have a character. Anyways, I choose Aether and hit Next and the screen turns black with the loading wheel thing spinning in the bottom right corner and seems to be stuck there. The wheel keeps spinning but the screen never changes.
What did I do wrong and how do I fix this?
Thank you in advance.

I am using a MacBook Pro 16”, M1 Pro with 16 GB
Monterey 12.1

**Comment by seathasky** [comment]
https://github.com/seathasky/FF14-MAC_ModSupport#infinite-black-screen-fix
