### ISSUE TITLE
New recurring dx11 game crash

### ISSUE THREAD

**Issue by quangxdu** [seathasky/FF14-MAC_ModSupport#51]
M1 max 14 inch, 32 gb ram.  
DXVK patch 1.9.2-async.
moltenVK 1.1.6
<img width="1512" alt="Screen Shot 2021-12-22 at 9 52 08 PM" src="https://user-images.githubusercontent.com/6291350/147185578-8ef86f50-f875-4024-957e-2804f104b40a.png">

**Comment by seathasky** [comment]
What version of CX are you using?

**Comment by FleetAdmiralButter** [comment]
Hey @quangxdu, have you manually made any changes to the environment variables in cxbottle.conf? If not, could you post the contents of the file here?

**Comment by quangxdu** [comment]
CX21, I managed to resolve the issue by resetting the version of dxvk used by crossover.

**Comment by seathasky** [comment]
If you need more assistance, join us in discord.
