### ISSUE TITLE
XIV launcher failed to check for updates

### ISSUE THREAD

**Issue by ReiArp** [seathasky/FF14-MAC_ModSupport#52]
<img width="432" alt="Screen Shot 2022-02-10 at 07 09 40" src="https://user-images.githubusercontent.com/98978749/153402388-8ed4f305-1a58-4fdb-a609-544dd20da490.png">
Anyone experience with this error?

**Comment by seathasky** [comment]
We no longer support this guide. Use XIV on Mac.
