### ISSUE TITLE
The Square Enix Account Unable To Play

### ISSUE THREAD

**Issue by pinkybeans** [seathasky/FF14-MAC_ModSupport#53]
![unable](https://user-images.githubusercontent.com/99928131/154593589-853f00b9-9e74-4d7c-b572-d5be85846c31.png)

download for my Mac M1, already activated on mog station, status standard and up running until March 18. but still unable to login. what should i do? contact Square Enix or reinstall everything and retry? bcs i dont want to run the application without crossover or else itll stuck my whole :')

**Comment by seathasky** [comment]
![Screen Shot 2022-02-17 at 7 50 42 PM](https://user-images.githubusercontent.com/17598024/154596465-cc9ce46c-c695-462f-83fa-a6d27018dc2b.png)
Make sure you have the correct license set.

**Comment by pinkybeans** [comment]
> 

i tried to find the license, but it doesnt show up when i click the launcher and crossover.
![licesne](https://user-images.githubusercontent.com/99928131/154601652-1a7703b8-066e-4b32-b092-16f1a424b386.png)
![joke](https://user-images.githubusercontent.com/99928131/154601646-8699eeda-a8fb-485d-9b42-dc223ab7efda.png)

**Comment by seathasky** [comment]
Oh my bad. Wrong project. Sorry I was referring to the new project. The CX project has been discontinued. Clearly says it on the opening statement of the github, use XIV on Mac instead.
