### ISSUE TITLE
Unable to run install script for Windows account

### ISSUE THREAD

**Issue by Knalik** [seathasky/FF14-MAC_ModSupport#6]
I may be making a very silly mistake, but I can't seem to run Marzents install.sh file to get ffxiv launcher to recognize my Windows account. I have followed the steps up to logging into the launcher and installing but have gotten stuck running the script and changing files in regedit. If running the script in either terminal or script edit is not correct, how should I be going about it?

**Comment by seathasky** [comment]
Open Terminal type "cd" space and drag the un-ziped "ffxiv-on-mac" folder into the terminal window after cd and press enter


![Screen Shot 2021-11-02 at 4 05 49 PM](https://user-images.githubusercontent.com/17598024/139944443-beefb264-e9cc-44e9-96dc-d554cf0bc5b2.png)

then drag the "install.sh" file into the window and press enter again
![Screen Shot 2021-11-02 at 4 08 09 PM](https://user-images.githubusercontent.com/17598024/139944711-9dcffde5-ddbd-41fc-9e4a-873e470688d6.png)

If you see "Patching Crossover
You can now follow the rest of the install guide!"

You're good to go.

**Comment by Knalik** [comment]
Perfect! 

That did the trick. 

Thank you very much for all the hard work on this and the very quick reply!

**Comment by seathasky** [comment]
You're welcome! Enjoy!
