### ISSUE TITLE
"This Square Enix account cannot play FINAL FANTASY XIV" error in FFXIVLauncher after install.

### ISSUE THREAD

**Issue by Amperthorpe** [seathasky/FF14-MAC_ModSupport#7]
...and yes it's the right account, I checked by logging into the Lodestone and it works fine. :P

I followed the install steps using the .tie. I didn't run the script to allow modding at first, so after it didn't work the first time I ran the script, deleted the bottle, and installed it again. The launcher starts but has the same error as soon as I click log in. 

I only have a Window license, so maybe that's the problem? I didn't see anyone else reference this specific issue.

**Comment by seathasky** [comment]
https://github.com/seathasky/FF14-MAC_ModSupport#step-8-optional---so-you-want-to-use-your-ff14-windows-license-instead-of-the-mac-one

**Comment by seathasky** [comment]
Additionally if you dont know how to open regedit in crossover, Task manager, file, New task (run), type regedit, find Wine folder change hidewineexports to 1

![Screen Shot 2021-11-03 at 1 31 17 AM](https://user-images.githubusercontent.com/17598024/140013830-ae2e69ba-f26f-425a-b33a-cea598c8d343.png)


![Screen Shot 2021-11-03 at 1 34 26 AM](https://user-images.githubusercontent.com/17598024/140014044-79e84a4d-9629-4343-befb-a9dfa42e6840.png)

**Comment by Amperthorpe** [comment]
Ah, I didn't think I would need to complete the following steps until the game launched at all. That and the registry edit fixed it, downloading the game now. Thanks!

**Comment by seathasky** [comment]
GG! Have fun!

**Comment by saki117** [comment]
I am using a Mac license, after the Launcher auto updated, I got the same problem.

I'v tried to modify the HideWineExports value in regedit from 0 to 2, but still cannot login...

**Comment by kailred** [comment]
I am having this issue as well as of 30 minutes ago, it worked fine earlier this evening, quit the program. Reopened, encountering this error now. Have tried editing HideWineExports as well and it still tells me this error message.

Edit for info: I only have a Mac license, and never went through initial steps to use a windows license with this.

**Comment by seathasky** [comment]
You can thank **Goat** for all of this frustration. **Marzent** literally has a fix for this yet, **Goat (xivlauncher main dev)** is being stubborn and wont merge **Marzent's** pull request. This would fix everything for Mac licenses on updates.

We actually talk about this in our guide a little bit that the Mac client will break on updates here: 
https://github.com/seathasky/FF14-MAC_ModSupport#important
or on marzents page here: https://github.com/marzent/ffxiv-on-mac/tree/main#what-works

I spoke with @marzent a few minutes ago and he said Mac licenses should be fixed. If you are still having issues, please use our XIVLauncher Mac installer here: https://github.com/marzent/FFXIVQuickLauncher/releases/download/6.0.12/XIVLauncherWine.exe

I also made a big post about all of this here: https://github.com/seathasky/FF14-MAC_ModSupport/issues/15

**Comment by saki117** [comment]
It works, thankyou! 

> I spoke with @marzent a few minutes ago and he said Mac licenses should be fixed. If you are still having issues, please use our XIVLauncher Mac installer here: https://github.com/marzent/FFXIVQuickLauncher/releases/download/6.0.12/XIVLauncherWine.exe

**Comment by seathasky** [comment]
> It works, thankyou!
> 

You're welcome! Sorry for the frustration. Some things are out of our control (especially with 3rd party tools like xivlauncher) but we try our best to facilitate. Glad the fix worked for you!

**Comment by BenW125** [comment]
Is the launcher currently working with Steam licenses? I'm getting the same error on an active account with the "Use Steam service account" box ticked.

**Comment by seathasky** [comment]
If the bottle is set correctly to use windows licenses yes

**Comment by BenW125** [comment]
I thought that step was for Windows-only (specifically non-Steam) licenses, so I was scared to touch it. Seems to be working now! Thanks so much!

**Comment by seathasky** [comment]
There is no such thing as a Mac Steam license, also our guide for Steam is in the windows section :)

ANDDDDDD
Directly from steam: 
![Screen Shot 2021-11-15 at 1 03 06 AM](https://user-images.githubusercontent.com/17598024/141730515-bb270497-74ed-4459-85a7-4d6d7d591090.png)
