### ISSUE TITLE
Odd rendering ingame?

### ISSUE THREAD

**Issue by ryielle** [seathasky/FF14-MAC_ModSupport#8]
Hey,

Thanks for all the work on this!
Using the tie and following the instructions (I have not yet done the instructions for the mods yet), I'm able to log in - but the rendering doesn't seem quite right - I've attached a screenshot of Eulmore:

<img width="1800" alt="Screenshot 2021-11-03 at 15 21 17" src="https://user-images.githubusercontent.com/25732134/140092840-6953a7e6-864d-4a4f-a9c5-0bded81ae8fa.png">

Is there a piece of configuration I'm missing? I had a look at the crossover site / wine hq discussion for this game but I haven't found anything yet (or my searching skills need work).

I:
- Am running CrossOver 21.0.0.33720
- Am running macOS 12.0.1 
- Am on a MBP 14 M1 Max
- Used the install script (though that looks like it's mostly for the network stuff)
- Installed the bottle using the tie, but some of the .NET framework dependencies got stuck and I had to cancel them (I installed them into the bottle manually later, and thought I was successful doing so)
- Have a Steam licence, and needed to configure the launcher such that it says "Wine on Linux" (step 8)
- Set the environment variables as per step 2
- Set the bottle settings as per step 3
- Had to set CutsceneMovieOpening to 1
- Haven't done step 4, 6, 7

Is there some rendering / directx config problem I've missed somewhere?

Thanks!

**Comment by seathasky** [comment]
**Hi there. Make sure you have HBAO turned "OFF" in settings. Should fix this issue.**

![Screen Shot 2021-11-03 at 1 42 54 PM](https://user-images.githubusercontent.com/17598024/140163480-79c0a009-6592-4004-a4f9-787dd0fc5af4.png)

**I can replicate your issue by turning that setting on:**

![Screen Shot 2021-11-03 at 1 44 46 PM](https://user-images.githubusercontent.com/17598024/140163809-78b40598-2f59-4ff7-a1fc-df930a2aa2c4.png)

**Comment by ryielle** [comment]
That was it, thank you so much!
Sorry if I missed some documentation...
