### ISSUE TITLE
Black screen/infinite loading animation after data center select

### ISSUE THREAD

**Issue by videodromejockey** [seathasky/FF14-MAC_ModSupport#9]
I followed the directions on a fresh install of Crossover. I've gotten the game to launch without a problem using my Windows license. However, when I select the data center, it goes to a black screen with an infinite loading animation in the bottom right and never goes further. Any advice?

**Comment by seathasky** [comment]
issue is covered here: https://github.com/seathasky/FF14-MAC_ModSupport#troubleshooting

**Comment by videodromejockey** [comment]
CutsceneMovieOpening is already set to 0.

**Comment by seathasky** [comment]
It should be set to 1

**Comment by videodromejockey** [comment]
Ok, troubleshooting section should probably be changed to say that. Thanks!

**Comment by seathasky** [comment]
you're welcome
